begin;
select plan(35);

select has_table('public','checklist_submissions','submission table exists');
select has_table('public','opening_item_results','opening results exist');
select has_table('public','hygiene_staff_snapshots','hygiene snapshots exist');
select has_table('public','checklist_issues','issues exist');
select has_table('public','checklist_submission_idempotency','idempotency exists');
select col_is_pk('public','checklist_submissions','id','submission UUID PK');
select col_is_pk('public','opening_item_results','id','opening UUID PK');
select col_is_pk('public','hygiene_staff_snapshots','id','hygiene UUID PK');
select col_is_pk('public','checklist_issues','id','issue UUID PK');
select is((select count(*) from public.checklist_definition_items where definition_id='kitchen_opening_v1'),17::bigint,'kitchen definition contains exactly 17 items');
select is((select count(*) from public.checklist_definition_items where definition_id='foh_opening_v1'),18::bigint,'FOH definition contains exactly 18 items');
select is((select count(*) from public.checklist_definition_items where definition_id='staff_hygiene_v1'),4::bigint,'hygiene has exactly four checks');
select is((select string_agg(item_id,',' order by ordinal) from public.checklist_definition_items where definition_id='kitchen_opening_v1'),(select string_agg('kitchen-opening-'||n,',' order by n) from generate_series(1,17)n),'kitchen stable IDs and order');
select is((select string_agg(item_id,',' order by ordinal) from public.checklist_definition_items where definition_id='foh_opening_v1'),(select string_agg('foh-opening-'||n,',' order by n) from generate_series(1,18)n),'FOH stable IDs and order');
select is((select string_agg(item_text, E'\n' order by ordinal) from public.checklist_definition_items where definition_id='staff_hygiene_v1'),E'Uniform\nFingernails\nHair / Haircut\nShave / Facial Hair','hygiene wording unchanged');
select throws_ok($$select private.phase4a_validate_opening('kitchen_opening_v1','[]'::jsonb,false)$$,'22023','invalid definition items','missing IDs rejected');
select throws_ok($$select private.phase4a_validate_opening('kitchen_opening_v1','[{"item_id":"unknown","answer":"completed","remark":"","evidence_id":null}]'::jsonb,false)$$,'22023','invalid definition items','unknown IDs rejected');
select throws_ok($$select private.phase4a_validate_opening('kitchen_opening_v1',(select jsonb_agg(jsonb_build_object('item_id','kitchen-opening-1','answer','completed','remark','','evidence_id',null)) from generate_series(1,17)),false)$$,'22023','invalid definition items','duplicate IDs rejected');
select throws_ok($$select private.phase4a_validate_opening('kitchen_opening_v1',(select jsonb_agg(jsonb_build_object('item_id','foh-opening-'||n,'answer','completed','remark','','evidence_id',null)) from generate_series(1,17)n),false)$$,'22023','invalid answer','cross-checklist IDs rejected');
select throws_ok($$select private.phase4a_validate_opening('kitchen_opening_v1',(select jsonb_agg(jsonb_build_object('item_id','kitchen-opening-'||n,'answer',case when n=1 then 'not_checked' else 'completed' end,'remark','','evidence_id',null) order by n) from generate_series(1,17)n),true)$$,'22023','invalid answer','pending final answer rejected');
select throws_ok($$select private.phase4a_validate_opening('kitchen_opening_v1',(select jsonb_agg(jsonb_build_object('item_id','kitchen-opening-'||n,'answer',case when n=1 then 'issue_found' else 'completed' end,'remark','','evidence_id',case when n=1 then to_jsonb('71000000-0000-4000-8000-000000000001'::text) else 'null'::jsonb end) order by n) from generate_series(1,17)n),true)$$,'22023','invalid answer','unremarked issue rejected');
select ok((select relrowsecurity from pg_class where oid='public.checklist_submissions'::regclass),'report RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.opening_item_results'::regclass),'opening RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.hygiene_staff_snapshots'::regclass),'hygiene RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.checklist_issues'::regclass),'issues RLS enabled');
select ok((select relrowsecurity from pg_class where oid='public.checklist_submission_idempotency'::regclass),'idempotency RLS enabled');
select is(has_function_privilege('anon','public.save_phase4a_draft(uuid,uuid,text,bigint,jsonb)','execute'),false,'anon cannot save drafts');
select is(has_function_privilege('authenticated','public.save_phase4a_draft(uuid,uuid,text,bigint,jsonb)','execute'),false,'authenticated cannot execute trusted draft RPC');
select is(has_function_privilege('service_role','public.save_phase4a_draft(uuid,uuid,text,bigint,jsonb)','execute'),true,'service role may execute narrow draft RPC');
select is(has_function_privilege('authenticated','public.submit_phase4a_opening(uuid,uuid,text,bigint,uuid,text,jsonb)','execute'),false,'authenticated cannot execute opening mutation RPC');
select is(has_function_privilege('authenticated','public.submit_phase4a_hygiene(uuid,uuid,uuid,text,jsonb)','execute'),false,'authenticated cannot execute hygiene mutation RPC');
select has_index('public','checklist_submissions','checklist_submissions_branch_date_type_idx','branch/date/type index');
select has_index('public','checklist_submissions','checklist_submissions_team_date_idx','team/date index');
select has_index('public','checklist_issues','checklist_issues_source_idx','issue source index');
select is((select count(*) from information_schema.columns where table_schema='public' and table_name in ('checklist_submissions','opening_item_results','hygiene_staff_snapshots','checklist_issues') and column_name in ('password','pin','token','cookie','email')),0::bigint,'reports contain no secret-bearing or email fields');
select * from finish();
rollback;
