import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { createPinCrypto } from "./admin";
import { validateDailyAuditGrant, validateManualDailyAuditGrant } from "./daily-audit-grant";

const actor="10000000-0000-4000-8000-000000000001", org="20000000-0000-4000-8000-000000000001", branch="30000000-0000-4000-8000-000000000001", other="30000000-0000-4000-8000-000000000002", user="40000000-0000-4000-8000-000000000001", version="50000000-0000-4000-8000-000000000001";
describe("Daily Audit v2 manual grant",()=>{
 it("validates same-org branches and returns safe auditor identity",async()=>{const crypto=createPinCrypto("test-daily-audit-secret");const grant=crypto.issueManualDailyAuditGrant!({actorUserId:actor,organizationId:org,originalBranchId:branch,auditorId:user,auditorDisplayName:"Audit Runner",credentialVersion:version,now:Date.now()});const identity=await validateManualDailyAuditGrant({cookies:`audit_access=${grant}`,actorUserId:actor,targetBranchId:other,pinCrypto:crypto,getBranchScope:async()=>({organization_id:org,active:true}),getCredentialScope:async()=>({active:true,credential_version:version,display_name:"Audit Runner"})});assert.deepEqual(identity,{organization_id:org,branch_id:other,original_branch_id:branch,auditor_kind:"manual_access_user",auditor_id:user,auditor_display_name:"Audit Runner",access_credential_version:version});assert.doesNotMatch(JSON.stringify(identity),/pin_hash|salt|grant|token/i);});
 it("rejects cross-org, revoked, mismatched, expired, and actor-mismatched grants",async()=>{const crypto=createPinCrypto("test-daily-audit-secret");const grant=crypto.issueManualDailyAuditGrant!({actorUserId:actor,organizationId:org,originalBranchId:branch,auditorId:user,auditorDisplayName:"Audit Runner",credentialVersion:version,now:Date.now()-6*60_000});const base={cookies:`audit_access=${grant}`,actorUserId:actor,targetBranchId:other,pinCrypto:crypto,getBranchScope:async()=>({organization_id:org,active:true}),getCredentialScope:async()=>({active:true,credential_version:version,display_name:"Audit Runner"})};assert.equal(await validateManualDailyAuditGrant(base),null);assert.equal(await validateManualDailyAuditGrant({...base,targetBranchId:other,getBranchScope:async()=>({organization_id:"60000000-0000-4000-8000-000000000001",active:true})}),null);assert.equal(await validateManualDailyAuditGrant({...base,getCredentialScope:async()=>({active:false,credential_version:version,display_name:"Audit Runner"})}),null);});
});

describe("Daily Audit v2 Organization Manager PIN grant",()=>{
 it("validates for another active branch and preserves the signed Manager name snapshot",async()=>{const crypto=createPinCrypto("test-daily-audit-secret");const grant=crypto.issueOrganizationManagerDailyAuditGrant!({actorUserId:actor,organizationId:org,originalBranchId:branch,auditorId:user,auditorDisplayName:"Manager Nadia",credentialVersion:version,now:Date.now()});const identity=await validateDailyAuditGrant({cookies:`audit_access=${grant}`,actorUserId:actor,targetBranchId:other,pinCrypto:crypto,getBranchScope:async()=>({organization_id:org,active:true}),getCredentialScope:async()=>null,getOrganizationManagerCredentialScope:async()=>({active:true,credential_version:version,display_name:"Organization Manager"})});assert.deepEqual(identity,{organization_id:org,branch_id:other,original_branch_id:branch,auditor_kind:"organization_manager_pin",auditor_id:user,auditor_display_name:"Manager Nadia",access_credential_version:version});assert.doesNotMatch(JSON.stringify(identity),/pin_hash|salt|grant|token/i);});
 it("rejects legacy, cross-org, inactive, version-mismatched, expired, and actor-mismatched grants",async()=>{const crypto=createPinCrypto("test-daily-audit-secret"),now=Date.now();const legacy=crypto.issueManagerGrant!(actor,branch,org,user,version,now);const current=crypto.issueOrganizationManagerDailyAuditGrant!({actorUserId:actor,organizationId:org,originalBranchId:branch,auditorId:user,auditorDisplayName:"Organization Manager",credentialVersion:version,now});const base={cookies:`audit_access=${current}`,actorUserId:actor,targetBranchId:other,pinCrypto:crypto,getBranchScope:async()=>({organization_id:org,active:true}),getCredentialScope:async()=>null,getOrganizationManagerCredentialScope:async()=>({active:true,credential_version:version,display_name:"Organization Manager"})};assert.equal(await validateDailyAuditGrant({...base,cookies:`audit_access=${legacy}`}),null);assert.equal(await validateDailyAuditGrant({...base,getBranchScope:async()=>({organization_id:"60000000-0000-4000-8000-000000000001",active:true})}),null);assert.equal(await validateDailyAuditGrant({...base,getOrganizationManagerCredentialScope:async()=>({active:false,credential_version:version,display_name:"Organization Manager"})}),null);assert.equal(await validateDailyAuditGrant({...base,getOrganizationManagerCredentialScope:async()=>({active:true,credential_version:"70000000-0000-4000-8000-000000000001",display_name:"Organization Manager"})}),null);assert.equal(await validateDailyAuditGrant({...base,cookies:`audit_access=${crypto.issueOrganizationManagerDailyAuditGrant!({actorUserId:actor,organizationId:org,originalBranchId:branch,auditorId:user,auditorDisplayName:"Organization Manager",credentialVersion:version,now:now-6*60_000})}`}),null);assert.equal(await validateDailyAuditGrant({...base,actorUserId:"80000000-0000-4000-8000-000000000001"}),null);});
});
