import assert from "node:assert/strict";
import { createServer } from "node:http";
import type { AddressInfo } from "node:net";
import { afterEach, describe, it } from "node:test";
import { AdminAccessError, AdminConflictError, createPinCrypto, type DailyAuditAccessUserCredential, type ManagerPinCredential } from "./admin";
import { createApp } from "./app";
import { loadBackendConfig } from "./config";
import type { BackendDependencies } from "./dependencies";

const ids={actor:"16000000-0000-4000-8000-000000000001",manager:"16000000-0000-4000-8000-000000000002",organization:"26000000-0000-4000-8000-000000000001",branch:"36000000-0000-4000-8000-000000000001",branchB:"36000000-0000-4000-8000-000000000002",version:"46000000-0000-4000-8000-000000000001"};
const config=loadBackendConfig({NODE_ENV:"test",SUPABASE_URL:"http://127.0.0.1:54321",SUPABASE_PUBLISHABLE_KEY:"test-placeholder",DAILY_AUDIT_GRANT_SECRET:"test-daily-audit-grant-secret-placeholder-32-bytes"});
const servers:ReturnType<typeof createServer>[]=[];
const credential:ManagerPinCredential={organization_id:ids.organization,manager_user_id:ids.manager,display_name:"Manager Nadia",pin_hash:"\\x"+"11".repeat(32),salt:"\\x"+"22".repeat(16),kdf_version:1,cost:16384,block_size:8,parallelization:1,credential_version:ids.version};
const manualCredential:DailyAuditAccessUserCredential={organization_id:ids.organization,access_user_id:"56000000-0000-4000-8000-000000000001",display_name:"Audit Runner",pin_hash:"\\x"+"44".repeat(32),salt:"\\x"+"55".repeat(16),kdf_version:1,cost:16384,block_size:8,parallelization:1,credential_version:"56000000-0000-4000-8000-000000000002"};

function deps(options:{manager?:boolean;internalAdmin?:boolean;verified?:boolean;conflict?:boolean;denied?:boolean;manualCredentials?:boolean;calls?:Record<string,unknown>}={}):BackendDependencies {
  const calls=options.calls??{};
  return {
    authVerifier:{async verify(token){return token==="valid"?{userId:ids.actor,email:"actor@example.invalid"}:null;}},
    async checkReadiness(){return true;},
    createUserContext(){return{async getUserContext(){return{id:ids.actor,full_name:"Actor",must_change_password:false,disabled:false,branches:[],managed_organizations:[]};},async isInternalAdmin(){return options.internalAdmin??false;},async hasOrganizationManagerAccess(){return options.manager??true;},async validateActiveBranches(){return false;},async listActiveBranches(){return[];}};},
    passwordChange:{async verifyCurrent(){return true;},async updatePassword(){},async finalize(){}},
    provisioningAdmin:{async createUser(){return{id:ids.actor};},async deleteUser(){},async finalize(){}},
    managementAdmin:{async listUsers(){return{users:[],total:0};}},
    branchManagementAdmin:{async listBranches(){return[];},async listStaff(){return[];},async getPinMetadata(){throw new Error("legacy must not run");},async storePin(){throw new Error("legacy must not run");},async getPinCredential(){throw new Error("legacy must not run");}},
    dailyAuditPinAdmin:{
      async listManagers(){if(options.denied)throw new AdminAccessError();return[{manager_user_id:ids.manager,full_name:"Manager",email:"manager@example.invalid",account_status:"active",configured:true,updated_at:"2026-08-05T00:00:00Z",updated_by_name:"Actor"}];},
      async storeManagerPin(input){calls.store=input;if(options.conflict)throw new AdminConflictError();if(options.denied)throw new AdminAccessError();return{manager_user_id:ids.manager,configured:true,updated_at:"2026-08-05T00:00:00Z",updated_by_name:"Actor"};},
      async listCredentials(_actor,branch){calls.branch=branch;if(options.denied)throw new AdminAccessError();return[credential];},
      async recordGrant(input){calls.grant=input;},async validateGrant(){return true;},
      async listAccessUsers(actorUserId,organizationId){calls.listAccess={actorUserId,organizationId};if(options.denied)throw new AdminAccessError();return[{id:manualCredential.access_user_id,organization_id:ids.organization,display_name:"Audit Runner",active:true,created_at:"2026-08-05T00:00:00Z",updated_at:"2026-08-05T00:00:00Z",updated_by_name:"Manager"}];},
      async createAccessUser(input){calls.createAccess=input;if(options.conflict)throw new AdminConflictError();if(options.denied)throw new AdminAccessError();},
      async revokeAccessUser(input){calls.revokeAccess=input;if(options.denied)throw new AdminAccessError();},
      async listAccessUserCredentials(_actor,branch){calls.manualBranch=branch;if(options.denied)throw new AdminAccessError();return options.manualCredentials?[manualCredential]:[];},
      async listManagersForInternalAdmin(){if(options.denied)throw new AdminAccessError();return[{manager_user_id:ids.manager,full_name:"Manager",email:"manager@example.invalid",account_status:"active",configured:true,updated_at:"2026-08-05T00:00:00Z",updated_by_name:"Actor"}];},
      async storeManagerPinForInternalAdmin(input){calls.store=input;if(options.conflict)throw new AdminConflictError();if(options.denied)throw new AdminAccessError();return{manager_user_id:ids.manager,configured:true,updated_at:"2026-08-05T00:00:00Z",updated_by_name:"Actor"};},
      async listAccessUsersForInternalAdmin(actorUserId,organizationId){calls.listAccess={actorUserId,organizationId};if(options.denied)throw new AdminAccessError();return[{id:manualCredential.access_user_id,organization_id:ids.organization,display_name:"Audit Runner",active:true,created_at:"2026-08-05T00:00:00Z",updated_at:"2026-08-05T00:00:00Z",updated_by_name:"Internal Admin"}];},
      async createAccessUserForInternalAdmin(input){calls.createAccess=input;if(options.conflict)throw new AdminConflictError();if(options.denied)throw new AdminAccessError();},
      async revokeAccessUserForInternalAdmin(input){calls.revokeAccess=input;if(options.denied)throw new AdminAccessError();},
    },
    pinCrypto:{
      async hash(pin){calls.hashedPin=pin;return credential;},fingerprint(pin){calls.fingerprintedPin=pin;return"\\x"+"33".repeat(32);},
      async verify(pin){calls.verifiedPin=pin;return options.verified??true;},
      issueManagerGrant(user,branch,organization,manager,version){calls.grantBinding={user,branch,organization,manager,version};return"opaque-manager-grant";},
      verifyManagerGrant(){return false;},issueGrant(user,branch,version){calls.manualGrantBinding={user,branch,version};return"opaque-manual-grant";},verifyGrant(){return false;},
      issueOrganizationManagerDailyAuditGrant(input){calls.managerV2GrantBinding=input;return"opaque-manager-v2-grant";},
      issueManualDailyAuditGrant(input){calls.manualV2GrantBinding=input;return"opaque-manual-v2-grant";},
    },
  };
}
async function start(dependencies:BackendDependencies){const server=createServer(createApp(config,dependencies));servers.push(server);await new Promise<void>(resolve=>server.listen(0,"127.0.0.1",resolve));return`http://127.0.0.1:${(server.address() as AddressInfo).port}`;}
afterEach(async()=>Promise.all(servers.splice(0).map(server=>new Promise<void>(resolve=>server.close(()=>resolve())))));
const request=(origin:string,path:string,init:RequestInit={})=>fetch(`${origin}${path}`,{...init,headers:{Authorization:"Bearer valid",...(init.headers??{})}});

describe("Internal Admin Daily Audit PIN API",()=>{
  it("returns only safe manager metadata and manual access users to an Internal Admin",async()=>{const origin=await start(deps({internalAdmin:true}));const response=await request(origin,`/api/v1/internal-admin/organizations/${ids.organization}/daily-audit-access`);assert.equal(response.status,200);const text=await response.text();assert.match(text,/Manager/);assert.match(text,/Audit Runner/);assert.doesNotMatch(text,/pin_hash|salt|fingerprint|credential_version|123456|1234/i);});
  it("lets an Internal Admin create and revoke organization-wide manual Daily Audit access users",async()=>{const calls:Record<string,unknown>={};const origin=await start(deps({calls,internalAdmin:true}));const create=await request(origin,`/api/v1/internal-admin/organizations/${ids.organization}/daily-audit-access`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({display_name:"  Audit Runner  ",pin:"1234",pin_confirmation:"1234"})});assert.equal(create.status,204);const revoke=await request(origin,`/api/v1/internal-admin/organizations/${ids.organization}/daily-audit-access/56000000-0000-4000-8000-000000000001`,{method:"DELETE"});assert.equal(revoke.status,204);assert.equal(calls.hashedPin,"1234");assert.deepEqual(calls.createAccess,{actorUserId:ids.actor,organizationId:ids.organization,displayName:"Audit Runner",credential});assert.deepEqual(calls.revokeAccess,{actorUserId:ids.actor,organizationId:ids.organization,accessUserId:"56000000-0000-4000-8000-000000000001"});});
  it("keeps old Manager Daily Audit provisioning endpoints fail closed",async()=>{const origin=await start(deps({manager:true}));assert.equal((await fetch(`${origin}/api/v1/management/organizations/${ids.organization}/daily-audit-pins`)).status,401);assert.equal((await request(origin,`/api/v1/management/organizations/${ids.organization}/daily-audit-pins`)).status,403);assert.equal((await request(origin,`/api/v1/management/organizations/${ids.organization}/daily-audit-access`)).status,403);assert.equal((await request(origin,`/api/v1/management/organizations/${ids.organization}/daily-audit-access`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({display_name:"Audit Runner",pin:"1234",pin_confirmation:"1234"})})).status,403);});
  it("denies Internal Admin Daily Audit access management to non-admins and invalid payloads",async()=>{const origin=await start(deps({internalAdmin:false}));assert.equal((await request(origin,`/api/v1/internal-admin/organizations/${ids.organization}/daily-audit-access`)).status,403);const admin=await start(deps({internalAdmin:true}));assert.equal((await request(admin,`/api/v1/internal-admin/organizations/${ids.organization}/daily-audit-access`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({branch_id:ids.branch,display_name:"Audit Runner",pin:"1234",pin_confirmation:"1234"})})).status,400);assert.equal((await request(admin,`/api/v1/internal-admin/organizations/${ids.organization}/daily-audit-access`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({display_name:"Audit Runner",pin:"12ab",pin_confirmation:"12ab"})})).status,400);assert.equal((await request(admin,`/api/v1/internal-admin/organizations/${ids.organization}/daily-audit-access/not-a-uuid`,{method:"DELETE"})).status,400);});
  it("strictly validates ASCII six digits, confirmation, and unknown fields",async()=>{const origin=await start(deps({internalAdmin:true}));for(const body of [{pin:"123456",pin_confirmation:"123456"},{pin:"12345",pin_confirmation:"12345"},{pin:"١٢٣٤٥٦",pin_confirmation:"١٢٣٤٥٦"},{pin:"123456",pin_confirmation:"123456",role:"organization_manager"}]){const response=await request(origin,`/api/v1/internal-admin/organizations/${ids.organization}/daily-audit-pins/${ids.manager}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});assert.equal(response.status,body.pin==="123456"&&Object.keys(body).length===2?200:400);}});
  it("hashes and fingerprints only at the trusted Internal Admin boundary without returning secrets",async()=>{const calls:Record<string,unknown>={};const origin=await start(deps({calls,internalAdmin:true}));const response=await request(origin,`/api/v1/internal-admin/organizations/${ids.organization}/daily-audit-pins/${ids.manager}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({pin:"123456",pin_confirmation:"123456"})});const text=await response.text();assert.equal(calls.hashedPin,"123456");assert.equal(calls.fingerprintedPin,"123456");assert.doesNotMatch(text,/123456|pin_hash|salt|fingerprint|credential_version/i);});
  it("maps duplicate and invalid targets to safe Internal Admin conflict/forbidden responses",async()=>{for(const [options,status] of [[{conflict:true,internalAdmin:true},409],[{denied:true,internalAdmin:true},403]] as const){const origin=await start(deps(options));const response=await request(origin,`/api/v1/internal-admin/organizations/${ids.organization}/daily-audit-pins/${ids.manager}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({pin:"123456",pin_confirmation:"123456"})});assert.equal(response.status,status);assert.doesNotMatch(await response.text(),/postgres|duplicate key|pin_hash|salt/i);}});
  it("derives organization and Manager owner from the authorized branch and issues a v2 cookie",async()=>{const calls:Record<string,unknown>={};const origin=await start(deps({calls,verified:true}));const response=await request(origin,"/api/v1/checklists/daily-audit/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({branch_id:ids.branch,pin:"123456"})});assert.equal(response.status,200);assert.equal(calls.branch,ids.branch);assert.deepEqual(calls.grant,{actorUserId:ids.actor,branchId:ids.branch,managerUserId:ids.manager,credentialVersion:ids.version});assert.deepEqual(calls.managerV2GrantBinding,{actorUserId:ids.actor,organizationId:ids.organization,originalBranchId:ids.branch,auditorId:ids.manager,auditorDisplayName:"Manager Nadia",credentialVersion:ids.version});assert.equal(calls.grantBinding,undefined);assert.match(response.headers.get("set-cookie")??"",/^audit_access=opaque-manager-v2-grant; Max-Age=300; Path=\/api\/daily-audit; HttpOnly; SameSite=Strict$/);assert.doesNotMatch(await response.text(),/manager|organization|credential|pin/i);});
  it("unlocks Daily Audit with an active manual access user PIN",async()=>{const calls:Record<string,unknown>={};const origin=await start(deps({calls,verified:true,manualCredentials:true}));const response=await request(origin,"/api/v1/checklists/daily-audit/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({branch_id:ids.branch,pin:"1234"})});assert.equal(response.status,200);assert.equal(calls.manualBranch,ids.branch);assert.deepEqual(calls.manualV2GrantBinding,{actorUserId:ids.actor,organizationId:ids.organization,originalBranchId:ids.branch,auditorId:manualCredential.access_user_id,auditorDisplayName:"Audit Runner",credentialVersion:manualCredential.credential_version});assert.equal(calls.manualGrantBinding,undefined);assert.equal(calls.branch,undefined);assert.equal(calls.grantBinding,undefined);assert.match(response.headers.get("set-cookie")??"",/^audit_access=opaque-manual-v2-grant; Max-Age=300; Path=\/api\/daily-audit; HttpOnly; SameSite=Strict$/);assert.doesNotMatch(await response.text(),/access_user|credential|pin|Audit Runner/i);});
  it("uses the same manual access user PIN for any branch in the organization",async()=>{const calls:Record<string,unknown>={};const origin=await start(deps({calls,verified:true,manualCredentials:true}));for(const branch of [ids.branch,ids.branchB]){const response=await request(origin,"/api/v1/checklists/daily-audit/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({branch_id:branch,pin:"1234"})});assert.equal(response.status,200);assert.deepEqual(calls.manualV2GrantBinding,{actorUserId:ids.actor,organizationId:ids.organization,originalBranchId:branch,auditorId:manualCredential.access_user_id,auditorDisplayName:"Audit Runner",credentialVersion:manualCredential.credential_version});}assert.equal(calls.grantBinding,undefined);});
  it("rejects client-supplied Manager authority and never accepts legacy branch PIN routes",async()=>{const origin=await start(deps());const verify=await request(origin,"/api/v1/checklists/daily-audit/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({branch_id:ids.branch,pin:"123456",manager_user_id:ids.manager})});assert.equal(verify.status,400);assert.equal((await request(origin,`/api/v1/branch-manager/branches/${ids.branch}/daily-audit-access`)).status,404);});
  it("returns one generic failure for wrong PIN or invalid Supervisor scope",async()=>{for(const options of [{verified:false},{denied:true}]){const origin=await start(deps(options));const response=await request(origin,"/api/v1/checklists/daily-audit/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({branch_id:ids.branch,pin:"123456"})});assert.equal(response.status,403);assert.equal((await response.json()).error.message,"Unable to verify Daily Audit access.");}});
  it("uses salted scrypt, tenant-scoped fingerprints, and fully bound grants",async()=>{const crypto=createPinCrypto("test-dedicated-grant-secret-placeholder-32-bytes");const first=await crypto.hash("123456"),second=await crypto.hash("123456");assert.notEqual(first.salt,second.salt);assert.equal(await crypto.verify("123456",first),true);assert.equal(crypto.fingerprint?.("123456"),crypto.fingerprint?.("123456"));const grant=crypto.issueManagerGrant?.(ids.actor,ids.branch,ids.organization,ids.manager,ids.version,1000)??"";assert.equal(crypto.verifyManagerGrant?.(grant,ids.actor,ids.branch,ids.organization,ids.manager,ids.version,300000),true);assert.equal(crypto.verifyManagerGrant?.(grant,ids.actor,ids.branchB,ids.organization,ids.manager,ids.version,300000),false);const payload=JSON.parse(Buffer.from(grant.split(".")[0],"base64url").toString());assert.deepEqual(Object.keys(payload).sort(),["aud","bid","exp","iat","mid","oid","sub","ver"]);assert.doesNotMatch(JSON.stringify(payload),/pin|hash|salt|password|secret/i);});
});
