import assert from "node:assert/strict";
import { createServer, type Server } from "node:http";
import type { AddressInfo } from "node:net";
import { afterEach, describe, it } from "node:test";
import { createPinCrypto, type ManagerPinCredential } from "./admin";
import { createApp } from "./app";
import { loadBackendConfig } from "./config";
import type { BackendDependencies } from "./dependencies";
import { OperationalConflictError } from "./operational";

const ids={actor:"11000000-0000-4000-8000-000000000001",manager:"11000000-0000-4000-8000-000000000002",organization:"21000000-0000-4000-8000-000000000001",otherOrganization:"21000000-0000-4000-8000-000000000002",branch:"31000000-0000-4000-8000-000000000001",sameOrgBranch:"31000000-0000-4000-8000-000000000002",crossOrgBranch:"31000000-0000-4000-8000-000000000003",version:"41000000-0000-4000-8000-000000000001"};
const config=loadBackendConfig({NODE_ENV:"test",SUPABASE_URL:"http://127.0.0.1:54321",SUPABASE_PUBLISHABLE_KEY:"test-placeholder",DAILY_AUDIT_GRANT_SECRET:"test-daily-audit-persistence-grant-secret"});
const crypto=createPinCrypto("test-daily-audit-persistence-grant-secret");
const servers:Server[]=[];
const items=Array.from({length:13},(_,index)=>({item_id:`daily-audit-${index+1}`,item_number:index+1,answer:"not_checked" as const,remark:""}));
const submittedItems=items.map((item)=>({...item,answer:"compliant" as const}));

async function dependencies(calls:Record<string,unknown>):Promise<BackendDependencies>{
 const hashed=await crypto.hash("123456");
 const credential:ManagerPinCredential={...hashed,organization_id:ids.organization,manager_user_id:ids.manager,display_name:"Manager Nadia",credential_version:ids.version};
 const result=(branchId:string,state:"empty"|"draft"|"submitted"="empty")=>({submission_id:state==="empty"?null:"51000000-0000-4000-8000-000000000001",branch_id:branchId,business_date:"2026-08-11",state,auditor_display_name:state==="empty"?null:"Manager Nadia",auditor_kind:state==="empty"?null:"organization_manager_pin",submitted_at:state==="submitted"?"2026-08-11T08:05:00.000Z":null,updated_at:state==="empty"?null:"2026-08-11T08:00:00.000Z",items:state==="submitted"?submittedItems:items});
 return {
  authVerifier:{async verify(token){return token==="valid"?{userId:ids.actor,email:"actor@example.invalid"}:null;}},async checkReadiness(){return true;},
  createUserContext(){return{async getUserContext(){return{id:ids.actor,full_name:"Supervisor",must_change_password:false,disabled:false,branches:[{id:ids.branch,name:"Branch",organization_id:ids.organization,role:"branch_manager" as const},{id:ids.sameOrgBranch,name:"Branch B",organization_id:ids.organization,role:"branch_manager" as const}],managed_organizations:[]};},async isInternalAdmin(){return false;},async hasOrganizationManagerAccess(){return false;},async validateActiveBranches(){return true;},async listActiveBranches(){return[];}};},
  passwordChange:{async verifyCurrent(){return true;},async updatePassword(){},async finalize(){}},provisioningAdmin:{async createUser(){return{id:ids.actor};},async deleteUser(){},async finalize(){}},managementAdmin:{async listUsers(){return{users:[],total:0};}},branchManagementAdmin:{async listBranches(){return[];},async listStaff(){return[];},async getPinMetadata(){return{configured:false,updated_at:null,updated_by_name:null};},async storePin(){return{configured:false,updated_at:null,updated_by_name:null};},async getPinCredential(){return null;}},
  dailyAuditPinAdmin:{async listManagers(){return[];},async storeManagerPin(){throw new Error("unused");},async listCredentials(){return[credential];},async recordGrant(input){calls.recorded=input;},async validateGrant(input){calls.validated=input;return input.managerUserId===ids.manager&&input.credentialVersion===ids.version&&[ids.branch,ids.sameOrgBranch].includes(input.branchId);}},
  pinCrypto:crypto,
  operationalAdmin:{
   async resolveDailyAuditGrantBranchScope(_actorUserId,branchId){if(branchId===ids.crossOrgBranch)return{branch_id:branchId,organization_id:ids.otherOrganization,active:true,organization_active:true};if([ids.branch,ids.sameOrgBranch].includes(branchId))return{branch_id:branchId,organization_id:ids.organization,active:true,organization_active:true};return null;},
   async resolveDailyAuditManualAccessUser(){return null;},
   async getSupervisorDailyAuditCurrentState(input){calls.current=input;return result(input.branchId);},
   async saveSupervisorDailyAuditDraft(input){calls.draft=input;if(calls.forceConflict)throw new OperationalConflictError();return result(input.branchId,"draft");},
   async submitSupervisorDailyAudit(input){calls.submit=input;if(calls.forceConflict)throw new OperationalConflictError();return result(input.branchId,"submitted");},
   async getBranchTimezone(){return"Asia/Riyadh";},async getSupervisorTeam(){return{teams:[]};},async createStaff(){return{};},async updateStaff(){return{};},async setDuty(){return{};},async listHealthCards(){return{health_cards:[]};},async upsertHealthCard(){return{};},async listMonthlyEvaluations(){return{evaluations:[]};},async saveMonthlyEvaluation(){return{};},async listPurchaseLogs(){return[];},async createPurchaseLog(){return{};},async updatePurchaseLogPaymentStatus(){return{};},async listSupplierReceivings(){return[];},async listBranchSuppliers(){return[];},async createBranchSupplier(){return{};},async createSupplierReceiving(){return{};},async listSupervisorMaintenanceIssues(){return[];},async createSupervisorMaintenanceIssue(){return{};},async listMaintenanceIssues(){return[];},async updateMaintenanceIssue(){return{};},async listMaintenancePurchases(){return[];},async createMaintenancePurchase(){return{};},async reimburseMaintenancePurchase(){return{};},async listManagedStaff(){return{};},async listManagedTeams(){return[];},async listEligibleSupervisors(){return[];},
  },
 };
}
async function start(deps:BackendDependencies){const server=createServer(createApp(config,deps));servers.push(server);await new Promise<void>(resolve=>server.listen(0,"127.0.0.1",resolve));return`http://127.0.0.1:${(server.address() as AddressInfo).port}`;}
afterEach(async()=>Promise.all(servers.splice(0).map(server=>new Promise<void>(resolve=>server.close(()=>resolve())))));
const request=(origin:string,path:string,init:RequestInit={})=>fetch(`${origin}${path}`,{...init,headers:{Authorization:"Bearer valid",...(init.headers??{})}});

describe("Daily Audit v2 grant persistence boundary",()=>{
 it("uses the Manager PIN verify cookie immediately for current-state and draft",async()=>{const calls:Record<string,unknown>={},origin=await start(await dependencies(calls));assert.equal((await fetch(`${origin}/api/v1/supervisor/branches/${ids.branch}/daily-audit/current-state?business_date=2026-08-11`)).status,401);const verify=await request(origin,"/api/v1/checklists/daily-audit/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({branch_id:ids.branch,pin:"123456"})});assert.equal(verify.status,200);const setCookie=verify.headers.get("set-cookie")??"";assert.match(setCookie,/^audit_access=/);assert.match(setCookie,/Path=\/api\/daily-audit/);const cookie=setCookie.split(";",1)[0];const current=await request(origin,`/api/v1/supervisor/branches/${ids.branch}/daily-audit/current-state?business_date=2026-08-11`,{headers:{Cookie:cookie}});assert.equal(current.status,200);assert.equal((await current.json()).items.length,13);const draft=await request(origin,`/api/v1/supervisor/branches/${ids.branch}/daily-audit/draft`,{method:"PUT",headers:{Cookie:cookie,"Content-Type":"application/json"},body:JSON.stringify({business_date:"2026-08-11",items:[]})});assert.equal(draft.status,200);assert.equal((calls.draft as {auditorKind:string}).auditorKind,"organization_manager_pin");assert.doesNotMatch(await draft.text(),/audit_access|grant|pin_hash|salt|credential_version/i);});
 it("submits exactly 13 known items with grant-derived auditor identity",async()=>{const calls:Record<string,unknown>={},origin=await start(await dependencies(calls));const verify=await request(origin,"/api/v1/checklists/daily-audit/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({branch_id:ids.branch,pin:"123456"})});const cookie=(verify.headers.get("set-cookie")??"").split(";",1)[0];const submit=await request(origin,`/api/v1/supervisor/branches/${ids.branch}/daily-audit/submit`,{method:"POST",headers:{Cookie:cookie,"Content-Type":"application/json","Idempotency-Key":"51000000-0000-4000-8000-000000000099"},body:JSON.stringify({business_date:"2026-08-11",items:submittedItems.map(({item_id,answer,remark})=>({item_id,answer,remark}))})});assert.equal(submit.status,201);const body=await submit.json();assert.equal(body.state,"submitted");assert.equal(body.items.length,13);assert.equal(body.items.filter((item:{answer:string})=>item.answer==="compliant").length,13);assert.deepEqual((calls.submit as {items:Array<{item_id:string;answer:string}>}).items.map((item)=>item.item_id),Array.from({length:13},(_,index)=>`daily-audit-${index+1}`));assert.equal((calls.submit as {auditorKind:string}).auditorKind,"organization_manager_pin");assert.equal((calls.submit as {auditorDisplayName:string}).auditorDisplayName,"Manager Nadia");assert.doesNotMatch(JSON.stringify(body),/audit_access|grant|pin_hash|salt|credential_version/i);});
 it("allows the v2 grant on another same-org branch but denies cross-org and invalid cookies",async()=>{const origin=await start(await dependencies({}));const verify=await request(origin,"/api/v1/checklists/daily-audit/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({branch_id:ids.branch,pin:"123456"})});const cookie=(verify.headers.get("set-cookie")??"").split(";",1)[0];assert.equal((await request(origin,`/api/v1/supervisor/branches/${ids.sameOrgBranch}/daily-audit/current-state?business_date=2026-08-11`,{headers:{Cookie:cookie}})).status,200);assert.equal((await request(origin,`/api/v1/supervisor/branches/${ids.crossOrgBranch}/daily-audit/current-state?business_date=2026-08-11`,{headers:{Cookie:cookie}})).status,403);assert.equal((await request(origin,`/api/v1/supervisor/branches/${ids.branch}/daily-audit/current-state?business_date=2026-08-11`)).status,403);assert.equal((await request(origin,`/api/v1/supervisor/branches/${ids.branch}/daily-audit/current-state?business_date=2026-08-11`,{headers:{Cookie:"audit_access=invalid"}})).status,403);});
 it("normalizes stale or already-submitted Daily Audit writes to a safe 409",async()=>{const calls:Record<string,unknown>={forceConflict:true},origin=await start(await dependencies(calls));const verify=await request(origin,"/api/v1/checklists/daily-audit/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({branch_id:ids.branch,pin:"123456"})});const cookie=(verify.headers.get("set-cookie")??"").split(";",1)[0];const draft=await request(origin,`/api/v1/supervisor/branches/${ids.branch}/daily-audit/draft`,{method:"PUT",headers:{Cookie:cookie,"Content-Type":"application/json"},body:JSON.stringify({business_date:"2026-08-11",expected_revision:1,items:[]})});assert.equal(draft.status,409);const body=JSON.stringify(await draft.json());assert.match(body,/conflict/i);assert.doesNotMatch(body,/40001|55000|postgres|supabase/i);});
});
