import assert from "node:assert/strict";
import { createServer,request as nodeRequest,type Server } from "node:http";
import type { AddressInfo } from "node:net";
import { after,before,describe,it } from "node:test";
import { createApp } from "./app";
import type { BackendConfig } from "./config";
import type { BackendDependencies } from "./dependencies";
import { createEvidenceServiceFromClient, EvidenceAccessError, EvidenceInputError, EvidenceUnavailableError, inspectEvidenceImage, MAX_EVIDENCE_BYTES, type EvidenceService } from "./evidence";

const supervisor="11000000-0000-4000-8000-000000000001";
const manager="11000000-0000-4000-8000-000000000002";
const branch="21000000-0000-4000-8000-000000000001";
const organization="31000000-0000-4000-8000-000000000001";
const evidenceId="41000000-0000-4000-8000-000000000001";
const item="kitchen-opening-1";
const jpeg=Buffer.from([0xff,0xd8,0xff,0xe0,0x00,0x00,0xff,0xd9]);
const png=Buffer.concat([Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]),Buffer.alloc(4),Buffer.from("IHDR"),Buffer.alloc(9),Buffer.alloc(4),Buffer.from("IEND"),Buffer.alloc(4)]);
const webp=Buffer.concat([Buffer.from("RIFF"),Buffer.alloc(4),Buffer.from("WEBP"),Buffer.alloc(8)]);webp.writeUInt32LE(webp.length-8,4);
const calls:Array<{name:string;input:unknown}>=[];
let uploadFailure:Error|null=null;
const evidenceService:EvidenceService={
 async upload(input){calls.push({name:"upload",input:{...input,bytes:Buffer.from(input.bytes)}});if(uploadFailure)throw uploadFailure;inspectEvidenceImage(input.bytes,input.declaredMime);return{id:evidenceId,status:"pending",mime_type:input.declaredMime as "image/jpeg",byte_size:input.bytes.length};},
 async retire(actorUserId,id){calls.push({name:"retire",input:{actorUserId,id}});if(actorUserId!==supervisor)throw new EvidenceAccessError();},
 async verifySet(actorUserId,branchId,type,ids){calls.push({name:"verify",input:{actorUserId,branchId,type,ids}});},
 async createReadUrl(actorUserId,id){calls.push({name:"read",input:{actorUserId,id}});if(actorUserId!==supervisor&&actorUserId!==manager)throw new EvidenceAccessError();return{evidence_id:id,signed_url:new URL("/storage/v1/object/sign/private","http://127.0.0.1:54321").toString(),expires_in:60,mime_type:"image/jpeg"};},
};
function deps():BackendDependencies{return{evidenceService,checkReadiness:async()=>true,passwordChange:{verifyCurrent:async()=>true,updatePassword:async()=>{},finalize:async()=>{}},provisioningAdmin:{createUser:async()=>({id:supervisor}),deleteUser:async()=>{},finalize:async()=>{}},managementAdmin:{listUsers:async()=>({users:[],total:0})},branchManagementAdmin:{listBranches:async()=>[],listStaff:async()=>[],getPinMetadata:async()=>({configured:false,updated_at:null,updated_by_name:null}),storePin:async()=>({configured:false,updated_at:null,updated_by_name:null}),getPinCredential:async()=>null},pinCrypto:{hash:async()=>({pin_hash:"x",salt:"x",kdf_version:1,cost:1,block_size:1,parallelization:1}),verify:async()=>false,issueGrant:()=>"",verifyGrant:()=>false},authVerifier:{verify:async(token)=>token==="supervisor"?{userId:supervisor,email:"supervisor@example.invalid"}:token==="manager"?{userId:manager,email:"manager@example.invalid"}:null},createUserContext:(token)=>({getUserContext:async()=>token==="supervisor"?{id:supervisor,full_name:"Supervisor",must_change_password:false,disabled:false,branches:[{id:branch,name:"Branch",organization_id:organization,role:"branch_manager"}],managed_organizations:[]}:{id:manager,full_name:"Manager",must_change_password:false,disabled:false,branches:[],managed_organizations:[{id:organization,name:"Org",role:"organization_manager"}]},hasOrganizationManagerAccess:async()=>token==="manager",validateActiveBranches:async()=>true,listActiveBranches:async()=>[]})};}
const config:BackendConfig={nodeEnv:"test",host:"127.0.0.1",port:1,trustProxy:false,supabase:{url:"http://127.0.0.1",publishableKey:"test",secretKey:"test"},dailyAuditGrantSecret:"test-placeholder-long-enough-for-tests"};
let server:Server,origin:string;
async function request(path:string,token?:string,init:RequestInit={}){return fetch(origin+path,{...init,headers:{...(token?{Authorization:`Bearer ${token}`}:{"x-no-auth":"1"}),...(init.headers??{})}});}
async function rawStatus(path:string,headers:Record<string,string>){return new Promise<number>((resolve,reject)=>{const target=new URL(path,origin);const req=nodeRequest(target,{method:"POST",headers},response=>{resolve(response.statusCode??0);response.resume();});req.once("error",reject);req.end();});}

describe("issue evidence image inspection",()=>{
 it("accepts only matching JPEG, PNG and WebP headers",()=>{assert.equal(inspectEvidenceImage(jpeg,"image/jpeg").extension,"jpg");assert.equal(inspectEvidenceImage(png,"image/png").extension,"png");assert.equal(inspectEvidenceImage(webp,"image/webp").extension,"webp");});
 it("rejects mismatch, SVG, GIF, PDF, HEIC, unknown, empty and oversized bytes",()=>{for(const [bytes,mime] of [[jpeg,"image/png"],[Buffer.from("<svg></svg>"),"image/svg+xml"],[Buffer.from("GIF89a"),"image/gif"],[Buffer.from("%PDF"),"application/pdf"],[Buffer.from("ftypheic"),"image/heic"],[Buffer.from("unknown"),"image/jpeg"],[Buffer.alloc(0),"image/png"],[Buffer.alloc(MAX_EVIDENCE_BYTES+1),"image/jpeg"]] as Array<[Buffer,string]>)assert.throws(()=>inspectEvidenceImage(bytes,mime),EvidenceInputError);});
});

describe("evidence storage/database compensation",()=>{
 function service(options:{uploadError?:boolean;registerError?:boolean;removeError?:boolean}={}){const removed:string[][]=[];let registered=0;const storage={upload:async()=>({data:options.uploadError?null:{path:"opaque"},error:options.uploadError?{message:"private"}:null}),remove:async(paths:string[])=>{removed.push(paths);return{data:null,error:options.removeError?{message:"private cleanup"}:null};},info:async()=>({data:null,error:{message:"unused"}}),createSignedUrl:async()=>({data:null,error:{message:"unused"}})};const client={storage:{from:()=>storage},rpc:async(name:string)=>{if(name==="retire_expired_phase4a_evidence")return{data:[],error:null};if(name==="authorize_phase4a_evidence_upload")return{data:[{organization_id:organization,branch_id:branch,supervisor_user_id:supervisor,supervisor_team_id:"4a000000-0000-4000-8000-000000000001",business_date:"2026-08-04"}],error:null};if(name==="register_phase4a_evidence_upload"){registered+=1;return options.registerError?{data:null,error:{code:"XX000"}}:{data:[{id:evidenceId,status:"pending",mime_type:"image/jpeg",byte_size:jpeg.length,retired_object_paths:[]}],error:null};}return{data:[],error:null};}};return{value:createEvidenceServiceFromClient(client as never),removed,get registered(){return registered;}};}
 it("does not register a usable row after storage failure",async()=>{const fake=service({uploadError:true});await assert.rejects(()=>fake.value.upload({actorUserId:supervisor,branchId:branch,checklistType:"kitchen_opening",itemId:item,bytes:jpeg,declaredMime:"image/jpeg",requestId:"safe-request"}),EvidenceUnavailableError);assert.equal(fake.registered,0);assert.equal(fake.removed.length,0);});
 it("removes the opaque object when database registration fails",async()=>{const fake=service({registerError:true});await assert.rejects(()=>fake.value.upload({actorUserId:supervisor,branchId:branch,checklistType:"kitchen_opening",itemId:item,bytes:jpeg,declaredMime:"image/jpeg",requestId:"safe-request"}),EvidenceUnavailableError);assert.equal(fake.registered,1);assert.equal(fake.removed.length,1);assert.doesNotMatch(fake.removed[0][0],/@|original|filename/i);});
 it("logs only bounded operational fields if compensation also fails",async()=>{const fake=service({registerError:true,removeError:true});const original=console.warn;const records:unknown[][]=[];console.warn=(...args)=>records.push(args);try{await assert.rejects(()=>fake.value.upload({actorUserId:supervisor,branchId:branch,checklistType:"kitchen_opening",itemId:item,bytes:jpeg,declaredMime:"image/jpeg",requestId:"safe-request"}),EvidenceUnavailableError);}finally{console.warn=original;}const serialized=JSON.stringify(records);assert.match(serialized,/safe-request/);assert.match(serialized,/storage_cleanup_failed/);assert.doesNotMatch(serialized,/Bearer|cookie|signed_url|email|remark|image\/jpeg|ffd8/i);});
});

describe("issue evidence API",()=>{
 before(async()=>{server=createServer(createApp(config,deps()));await new Promise<void>((resolve,reject)=>server.listen(0,"127.0.0.1",resolve).once("error",reject));origin=`http://127.0.0.1:${(server.address()as AddressInfo).port}`;});
 after(()=>new Promise<void>(resolve=>server.close(()=>resolve())));
 it("registers the upload route behind authentication (401, not 404)",async()=>{assert.equal((await request(`/api/v1/supervisor/branches/${branch}/checklists/kitchen_opening/items/${item}/evidence`,undefined,{method:"POST",headers:{"Content-Type":"image/jpeg","Content-Length":String(jpeg.length)},body:jpeg})).status,401);});
 it("uploads bounded raw bytes and returns only safe metadata",async()=>{const response=await request(`/api/v1/supervisor/branches/${branch}/checklists/kitchen_opening/items/${item}/evidence`,"supervisor",{method:"POST",headers:{"Content-Type":"image/jpeg","Content-Length":String(jpeg.length)},body:jpeg});assert.equal(response.status,201);assert.match(response.headers.get("cache-control")??"",/no-store/);assert.equal(response.headers.get("x-content-type-options"),"nosniff");assert.deepEqual(await response.json(),{evidence:{id:evidenceId,status:"pending",mime_type:"image/jpeg",byte_size:jpeg.length}});const input=calls.at(-1)?.input as {bytes:Buffer;actorUserId:string;branchId:string;checklistType:string;itemId:string};assert.deepEqual(input.bytes,jpeg);assert.equal(input.actorUserId,supervisor);assert.equal(input.branchId,branch);assert.equal(input.checklistType,"kitchen_opening");assert.equal(input.itemId,item);});
 it("rejects unknown metadata and excessive length before upload",async()=>{const path=`/api/v1/supervisor/branches/${branch}/checklists/kitchen_opening/items/${item}/evidence`;assert.equal((await request(path,"supervisor",{method:"POST",headers:{"Content-Type":"image/jpeg","x-evidence-path":"forbidden"},body:jpeg})).status,400);assert.equal(await rawStatus(path,{Authorization:"Bearer supervisor","Content-Type":"image/jpeg","Content-Length":String(MAX_EVIDENCE_BYTES+1)}),413);});
 it("sanitizes invalid image and authorization failures",async()=>{uploadFailure=new EvidenceInputError();let response=await request(`/api/v1/supervisor/branches/${branch}/checklists/kitchen_opening/items/${item}/evidence`,"supervisor",{method:"POST",headers:{"Content-Type":"image/jpeg","Content-Length":String(jpeg.length)},body:jpeg});assert.equal(response.status,422);assert.doesNotMatch(JSON.stringify(await response.json()),/stack|storage|checksum|path/i);uploadFailure=new EvidenceAccessError();response=await request(`/api/v1/supervisor/branches/${branch}/checklists/kitchen_opening/items/${item}/evidence`,"manager",{method:"POST",headers:{"Content-Type":"image/jpeg","Content-Length":String(jpeg.length)},body:jpeg});assert.equal(response.status,403);uploadFailure=null;});
 it("allows authorized retirement and short-lived read URLs without exposing paths",async()=>{assert.equal((await request(`/api/v1/evidence/${evidenceId}`,"supervisor",{method:"DELETE"})).status,204);assert.equal((await request(`/api/v1/evidence/${evidenceId}/read-url`,"supervisor")).status,200);const denied=await request(`/api/v1/evidence/${evidenceId}`,"manager",{method:"DELETE"});assert.equal(denied.status,403);});
 it("rate limits upload creation separately by authenticated user and branch",async()=>{const statuses:number[]=[];for(let index=0;index<15;index++)statuses.push((await request(`/api/v1/supervisor/branches/${branch}/checklists/kitchen_opening/items/${item}/evidence`,"supervisor",{method:"POST",headers:{"Content-Type":"image/jpeg","Content-Length":String(jpeg.length)},body:jpeg})).status);assert.ok(statuses.includes(429));});
});
