import assert from "node:assert/strict";
import { createServer,type Server } from "node:http";
import type { AddressInfo } from "node:net";
import { after,before,describe,it } from "node:test";
import { createApp } from "./app";
import type { BackendDependencies } from "./dependencies";
import type { BackendConfig } from "./config";

const supervisor="11000000-0000-4000-8000-000000000001",manager="11000000-0000-4000-8000-000000000002",branch="21000000-0000-4000-8000-000000000001",org="31000000-0000-4000-8000-000000000001",staff="41000000-0000-4000-8000-000000000001";
const operationalTeam="61000000-0000-4000-8000-000000000010";
const calls:Array<{name:string;input:unknown}>=[];
let managementOverviewMode:"valid"|"unknown"|"failure"="valid";
const emptyCounts={expected_checks:0,answered_checks:0,compliant_checks:0,issue_checks:0,pending_checks:0,completion_percentage:null,compliance_percentage:null};
const managementOverview={organization:{id:org,name:"Organization"},generated_at:"2026-08-01T00:00:00Z",date_context:"current_branch_local_business_day",summary:{active_branch_count:1,active_team_count:1,active_supervisor_account_count:1,active_operational_staff_count:0},totals:{expected_checks:49,answered_checks:0,compliant_checks:0,issue_checks:0,pending_checks:49,completion_percentage:0,compliance_percentage:null},local_dates:[{business_date:"2026-08-01",branch_count:1}],branches:[{branch_id:branch,branch_name:"A",branch_code:"A",timezone:"Asia/Riyadh",business_date:"2026-08-01",status:"ready",active_team_count:1,totals:{expected_checks:49,answered_checks:0,compliant_checks:0,issue_checks:0,pending_checks:49,completion_percentage:0,compliance_percentage:null},checklists:[{checklist_type:"kitchen_opening",team_states:{not_started:1,draft:0,submitted:0},expected_checks:17,answered_checks:0,compliant_checks:0,issue_checks:0,pending_checks:17,completion_percentage:0,compliance_percentage:null},{checklist_type:"foh_opening",team_states:{not_started:1,draft:0,submitted:0},expected_checks:18,answered_checks:0,compliant_checks:0,issue_checks:0,pending_checks:18,completion_percentage:0,compliance_percentage:null},{checklist_type:"staff_hygiene",team_states:{not_started:1,draft:0,submitted:0},...emptyCounts},{checklist_type:"oil_tracking",team_states:{not_started:1,draft:0,submitted:0},...emptyCounts},{checklist_type:"cold_storage",team_states:{not_started:1,draft:0,submitted:0},...emptyCounts},{checklist_type:"sales_tracking",team_states:{not_started:1,draft:0,submitted:0},expected_checks:1,answered_checks:0,compliant_checks:0,issue_checks:0,pending_checks:1,completion_percentage:0,compliance_percentage:null},{checklist_type:"daily_audit",team_states:{not_started:1,draft:0,submitted:0},expected_checks:13,answered_checks:0,compliant_checks:0,issue_checks:0,pending_checks:13,completion_percentage:0,compliance_percentage:null}]}]};
const persistence={
 async getOverview(){calls.push({name:"overview",input:null});return{business_date:"2026-08-01",totals:{expected_checks:37,answered_checks:0,compliant_checks:0,issue_checks:0,pending_checks:37,completion_percentage:0,compliance_percentage:null},checklists:[{checklist_type:"kitchen_opening",state:"not_started",expected_checks:17,answered_checks:0,compliant_checks:0,issue_checks:0,pending_checks:17,completion_percentage:0,compliance_percentage:null},{checklist_type:"foh_opening",state:"not_started",expected_checks:18,answered_checks:0,compliant_checks:0,issue_checks:0,pending_checks:18,completion_percentage:0,compliance_percentage:null},{checklist_type:"staff_hygiene",state:"not_started",expected_checks:0,answered_checks:0,compliant_checks:0,issue_checks:0,pending_checks:0,completion_percentage:null,compliance_percentage:null},{checklist_type:"oil_tracking",state:"not_started",expected_checks:2,answered_checks:0,compliant_checks:0,issue_checks:0,pending_checks:2,completion_percentage:0,compliance_percentage:null},{checklist_type:"cold_storage",state:"not_started",expected_checks:0,answered_checks:0,compliant_checks:0,issue_checks:0,pending_checks:0,completion_percentage:null,compliance_percentage:null}]};},
 async getManagementOverview(actor:string,organization:string){calls.push({name:"management-overview",input:{actor,organization}});if(managementOverviewMode==="failure")throw new Error("raw database details");if(managementOverviewMode==="unknown")return{...managementOverview,raw_error:"secret"};return managementOverview;},
 async getCurrentState(_a:string,_b:string,type:string){calls.push({name:"current",input:type});return{state:"draft",checklist_type:type,business_date:"2026-08-01",updated_at:"2026-08-01T00:00:00Z",submitted_at:null,staff:[]};},
 async getHygieneCurrentState(){calls.push({name:"hygiene-current",input:operationalTeam});return{state:"none",checklist_type:"staff_hygiene",business_date:"2026-08-01",id:null,created_at:null,updated_at:null,submitted_at:null,operational_team_id:operationalTeam,team_name:"Team A",can_write:true,revision:0,staff:[]};},
 async saveDraft(input:unknown){calls.push({name:"save",input});return{id:"51000000-0000-4000-8000-000000000001",business_date:"2026-08-01",checklist_type:"kitchen_opening",state:"draft"};},
 async saveHygieneDraft(input:unknown){calls.push({name:"hygiene-draft",input});return{id:"51000000-0000-4000-8000-000000000002",business_date:"2026-08-01",checklist_type:"staff_hygiene",state:"draft"};},
 async submitOpening(input:unknown){calls.push({name:"submit",input});return{id:"51000000-0000-4000-8000-000000000003",business_date:"2026-08-01",checklist_type:"kitchen_opening",state:"submitted",submitted_at:"2026-08-01T00:00:00Z",issue_count:1};},
 async submitHygiene(input:unknown){calls.push({name:"hygiene-submit",input});return{id:"51000000-0000-4000-8000-000000000004",business_date:"2026-08-01",checklist_type:"staff_hygiene",state:"submitted",submitted_at:"2026-08-01T00:00:00Z",issue_count:0};},
 async getOilTrackingCurrentState(){calls.push({name:"oil-current",input:null});return{business_date:"2026-08-01",opening_submitted:false,closing_submitted:false,rows:[]};},
 async getColdStorageCurrentState(){calls.push({name:"cold-current",input:null});return{business_date:"2026-08-01",state:"none",equipment:[],readings:[]};},
 async saveOilTrackingDraft(input:unknown){calls.push({name:"oil-draft",input});return{business_date:"2026-08-01",opening_submitted:false,closing_submitted:false,rows:[]};},
 async submitOilTrackingOpening(input:unknown){calls.push({name:"oil-opening",input});return{business_date:"2026-08-01",opening_submitted:true,closing_submitted:false,rows:[]};},
 async submitOilTrackingClosing(input:unknown){calls.push({name:"oil-closing",input});return{business_date:"2026-08-01",opening_submitted:false,closing_submitted:true,rows:[]};},
 async listSupervisor(input:unknown){calls.push({name:"history",input});return{reports:[],page:2,page_size:7,total:20};},async getReport(_a:string,id:string,managerMode:boolean){calls.push({name:"detail",input:{id,managerMode}});return{id,branch_id:branch,branch_name:"A",business_date:"2026-08-01",checklist_type:"kitchen_opening",definition_id:"kitchen_opening_v1",submitted_at:"2026-08-01T00:00:00Z",submitted_by:"Supervisor",completion:100,status:"compliant",issue_count:0,items:[],staff:[]};},
 async listManagedReports(input:unknown){calls.push({name:"reports",input});return{reports:[{id:"51000000-0000-4000-8000-000000000003",branch_id:branch,branch_name:"A",checklist_type:"kitchen_opening",business_date:"2026-08-01",submitted_at:"2026-08-01T00:00:00Z",submitted_by:"Supervisor",issue_count:0,status:"compliant"}],page:1,page_size:9,total:1};},async listManagedIssues(input:unknown){calls.push({name:"issues",input});return{issues:[],page:1,page_size:8,total:0};},async getManagedIssue(_a:string,_o:string,id:string){calls.push({name:"issue-detail",input:id});return{id,report_id:"51000000-0000-4000-8000-000000000003",branch_id:branch,branch_name:"A",business_date:"2026-08-01",submitted_by:"Supervisor",checklist_type:"kitchen_opening",item_id:"kitchen-1",item_text:"Check item",affected_staff_id:null,affected_staff_name:null,remark:"Issue",status:"new",created_at:"2026-08-01T00:00:00Z"};},
};
function deps():BackendDependencies{return{checkReadiness:async()=>true,checklistPersistence:persistence,passwordChange:{verifyCurrent:async()=>true,updatePassword:async()=>{},finalize:async()=>{}},provisioningAdmin:{createUser:async()=>({id:supervisor}),deleteUser:async()=>{},finalize:async()=>{}},managementAdmin:{listUsers:async()=>({users:[],total:0})},branchManagementAdmin:{listBranches:async()=>[],listStaff:async()=>[],getPinMetadata:async()=>({configured:false,updated_at:null,updated_by_name:null}),storePin:async()=>({configured:false,updated_at:null,updated_by_name:null}),getPinCredential:async()=>null},pinCrypto:{hash:async()=>({pin_hash:"x",salt:"x",kdf_version:1,cost:1,block_size:1,parallelization:1}),verify:async()=>false,issueGrant:()=>"",verifyGrant:()=>false},now:()=>new Date(2026,7,1,14,0,0),authVerifier:{verify:async token=>token==="supervisor"?{userId:supervisor,email:"s@example.invalid"}:token==="manager"?{userId:manager,email:"m@example.invalid"}:null},createUserContext:token=>({getUserContext:async()=>token==="supervisor"?{id:supervisor,full_name:"S",must_change_password:false,disabled:false,branches:[{id:branch,name:"A",organization_id:org,role:"branch_manager"}],managed_organizations:[]}:{id:manager,full_name:"M",must_change_password:false,disabled:false,branches:[],managed_organizations:[{id:org,name:"O",role:"organization_manager"}]},hasOrganizationManagerAccess:async()=>token==="manager",validateActiveBranches:async()=>true,listActiveBranches:async()=>[]})};}
const config:BackendConfig={nodeEnv:"test",host:"127.0.0.1",port:1,trustProxy:false,supabase:{url:"http://127.0.0.1",publishableKey:"test",secretKey:"test"},dailyAuditGrantSecret:"test-placeholder-long-enough-for-tests"};let server:Server,origin:string;
async function request(path:string,token?:string,init:RequestInit={}){return fetch(origin+path,{...init,headers:{...(token?{Authorization:`Bearer ${token}`}:{"x-no-auth":"1"}),...(init.headers??{})}});}
describe("Phase 4A API integration",()=>{before(async()=>{server=createServer(createApp(config,deps()));await new Promise<void>((resolve,reject)=>server.listen(0,"127.0.0.1",resolve).once("error",reject));origin=`http://127.0.0.1:${(server.address()as AddressInfo).port}`;});after(()=>new Promise<void>(resolve=>server.close(()=>resolve())));
 it("requires authentication and rejects unknown current-state types",async()=>{assert.equal((await request(`/api/v1/supervisor/branches/${branch}/checklists/kitchen_opening/draft`)).status,401);assert.equal((await request(`/api/v1/supervisor/branches/${branch}/checklists/nope/draft`,"supervisor")).status,400);});
 it("returns the safe current-state contract",async()=>{const r=await request(`/api/v1/supervisor/branches/${branch}/checklists/staff_hygiene/teams/${operationalTeam}/current-state`,"supervisor");assert.equal(r.status,200);assert.deepEqual(Object.keys(await r.json()),["current"]);});
 it("returns the strict Overview contract and rejects browser or Manager authority",async()=>{const r=await request(`/api/v1/supervisor/branches/${branch}/overview`,"supervisor");assert.equal(r.status,200);const body=await r.json();assert.equal(body.totals.expected_checks,37);assert.equal(body.totals.compliance_percentage,null);assert.equal(body.checklists.length,5);assert.ok(body.checklists.some((row:{checklist_type:string})=>row.checklist_type==="oil_tracking"));assert.ok(body.checklists.some((row:{checklist_type:string})=>row.checklist_type==="cold_storage"));assert.equal((await request(`/api/v1/supervisor/branches/${branch}/overview?business_date=2026-08-01`,"supervisor")).status,400);assert.equal((await request(`/api/v1/supervisor/branches/${branch}/overview`)).status,401);assert.equal((await request(`/api/v1/supervisor/branches/${branch}/overview`,"manager")).status,403);});
 it("returns the strict atomic Manager Overview and rejects browser authority",async()=>{managementOverviewMode="valid";const path=`/api/v1/management/organizations/${org}/overview`;assert.equal((await request(path)).status,401);assert.equal((await request(path,"supervisor")).status,403);assert.equal((await request(`${path}?business_date=2026-08-01`,"manager")).status,400);const result=await request(path,"manager");assert.equal(result.status,200);assert.equal(result.headers.get("cache-control"),"private, no-store");const body=await result.json();assert.equal(body.totals.expected_checks,49);assert.equal(body.branches[0].checklists.length,7);assert.ok(body.branches[0].checklists.some((row:{checklist_type:string})=>row.checklist_type==="oil_tracking"));assert.ok(body.branches[0].checklists.some((row:{checklist_type:string})=>row.checklist_type==="cold_storage"));assert.ok(body.branches[0].checklists.some((row:{checklist_type:string})=>row.checklist_type==="sales_tracking"));assert.ok(body.branches[0].checklists.some((row:{checklist_type:string})=>row.checklist_type==="daily_audit"));assert.equal(calls.at(-1)?.name,"management-overview");});
 it("fails closed for unknown fields, malformed dependencies, and unknown routes",async()=>{const path=`/api/v1/management/organizations/${org}/overview`;managementOverviewMode="unknown";let result=await request(path,"manager");assert.equal(result.status,503);assert.doesNotMatch(JSON.stringify(await result.json()),/secret|raw_error/i);managementOverviewMode="failure";result=await request(path,"manager");assert.equal(result.status,503);assert.doesNotMatch(JSON.stringify(await result.json()),/database|raw/i);managementOverviewMode="valid";result=await request(`/api/v1/management/organizations/${org}/overview/not-found`,"manager");assert.equal(result.status,404);assert.doesNotMatch(JSON.stringify(await result.json()),/stack|database|supabase/i);});
 it("strictly saves a team Hygiene draft and rejects browser authority",async()=>{const body={checklist_type:"staff_hygiene",operational_team_id:operationalTeam,expected_revision:0,staff:[{staff_id:staff,uniform:"pending",fingernails:"pass",hair:"issue",facial_hair:"pending",remark:"draft"}]};assert.equal((await request(`/api/v1/supervisor/branches/${branch}/checklists/draft`,"supervisor",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)})).status,200);assert.equal((await request(`/api/v1/supervisor/branches/${branch}/checklists/draft`,"supervisor",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({...body,business_date:"2026-01-01"})})).status,400);assert.equal(calls.at(-1)?.name,"hygiene-draft");});
 it("requires an idempotency UUID and rejects pending final hygiene",async()=>{const body={checklist_type:"staff_hygiene",operational_team_id:operationalTeam,staff:[{staff_id:staff,uniform:"pending",fingernails:"pass",hair:"pass",facial_hair:"pass",remark:""}]};assert.equal((await request(`/api/v1/supervisor/branches/${branch}/checklists/submit`,"supervisor",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)})).status,400);assert.equal((await request(`/api/v1/supervisor/branches/${branch}/checklists/submit`,"supervisor",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":"61000000-0000-4000-8000-000000000001"},body:JSON.stringify(body)})).status,400);});
 it("forwards Supervisor pagination and allowlists detail",async()=>{assert.equal((await request(`/api/v1/supervisor/branches/${branch}/submissions?page=2&page_size=7&checklist_type=foh_opening`,"supervisor")).status,200);assert.equal(calls.at(-1)?.name,"history");const r=await request(`/api/v1/supervisor/submissions/51000000-0000-4000-8000-000000000003`,"supervisor");assert.equal(r.status,200);assert.equal((await r.json()).email,undefined);});
 it("forwards all Manager report and issue filters",async()=>{await request(`/api/v1/management/organizations/${org}/reports?page=2&page_size=9&date_from=2026-01-01&date_to=2026-08-01&branch_id=${branch}&supervisor_user_id=${supervisor}&checklist_type=kitchen_opening&status=issues_found&search=x`,"manager");assert.equal(calls.at(-1)?.name,"reports");await request(`/api/v1/management/organizations/${org}/issues?page=2&page_size=8&date_from=2026-01-01&date_to=2026-08-01&branch_id=${branch}&supervisor_user_id=${supervisor}&staff_id=${staff}&checklist_type=staff_hygiene&status=new&search=x`,"manager");assert.equal(calls.at(-1)?.name,"issues");});
 it("registers Manager Reports and Issues list/detail routes with anonymous 401 and authorized 200 DTOs",async()=>{const reportId="51000000-0000-4000-8000-000000000003",issueId="61000000-0000-4000-8000-000000000003";for(const route of[`/api/v1/management/organizations/${org}/reports`,`/api/v1/management/organizations/${org}/reports/${reportId}`,`/api/v1/management/organizations/${org}/issues`,`/api/v1/management/organizations/${org}/issues/${issueId}`])assert.equal((await request(route)).status,401,route);const reports=await request(`/api/v1/management/organizations/${org}/reports?page=1&page_size=9`,"manager");assert.equal(reports.status,200);const reportBody=await reports.json();assert.equal(reportBody.reports[0].branch_name,"A");assert.equal(reportBody.reports[0].completion,undefined);assert.equal(reportBody.total,1);const issues=await request(`/api/v1/management/organizations/${org}/issues?page=1&page_size=8`,"manager");assert.equal(issues.status,200);assert.deepEqual(await issues.json(),{issues:[],page:1,page_size:8,total:0});assert.equal((await request(`/api/v1/management/organizations/${org}/reports/${reportId}`,"manager")).status,200);assert.equal((await request(`/api/v1/management/organizations/${org}/issues/${issueId}`,"manager")).status,200);});
 it("denies Supervisor Manager detail access and rejects unknown query fields",async()=>{assert.equal((await request(`/api/v1/management/organizations/${org}/reports/51000000-0000-4000-8000-000000000003`,"supervisor")).status,403);assert.equal((await request(`/api/v1/management/organizations/${org}/issues?unknown=x`,"manager")).status,400);});
});
