-- Preserve the Supplier Receiving API's established validation error while keeping
-- the Phase 2 branch-shared supplier upsert helper reusable by other callers.
create or replace function public.create_branch_supplier_receiving(actor_user_id uuid,target_branch_id uuid,payload jsonb)
returns setof public.branch_supplier_receivings language plpgsql security definer set search_path=''as $$declare c record;s public.branch_suppliers%rowtype;category text:=payload->>'category';supplier_en text:=private.clean_supplier_receiving_text(payload->>'supplier_name_en',null,120);supplier_ar text:=private.clean_supplier_receiving_text(payload->>'supplier_name_ar',null,120);unit_value text:=private.clean_supplier_receiving_text(payload->>'unit',null,40);notes_value text:=private.clean_supplier_receiving_text(payload->>'notes',null,2000);photo_path text:=private.clean_supplier_receiving_text(payload->>'photo_storage_path',null,260);photo_name text:=private.clean_supplier_receiving_text(payload->>'photo_original_name',null,180);supplier_uuid uuid;q numeric;begin
 select*into strict c from private.phase2_branch_context(actor_user_id,target_branch_id);if category not in('raw','frozen','juice')or unit_value is null then raise exception'invalid supplier receiving payload'using errcode='22023';end if;begin q:=(payload->>'quantity')::numeric;supplier_uuid:=nullif(payload->>'supplier_id','')::uuid;exception when others then raise exception'invalid supplier receiving payload'using errcode='22023';end;if q<=0 then raise exception'invalid supplier receiving payload'using errcode='22023';end if;
 if supplier_uuid is not null then select*into s from public.branch_suppliers x where x.id=supplier_uuid and x.organization_id=c.organization_id and x.branch_id=c.branch_id;if s.id is null then raise exception'supplier receiving access denied'using errcode='42501';end if;if s.supplier_name_ar is null and supplier_ar is not null then update public.branch_suppliers set supplier_name_ar=supplier_ar where id=s.id returning*into s;end if;else if supplier_en is null then raise exception'invalid supplier receiving payload'using errcode='22023';end if;s:=private.upsert_branch_supplier_for_branch(c.organization_id,c.branch_id,c.legacy_team_id,actor_user_id,supplier_en,supplier_ar);end if;
 return query insert into public.branch_supplier_receivings(organization_id,branch_id,supervisor_team_id,supplier_id,category,supplier_name_en,supplier_name_ar,quantity,unit,notes,photo_storage_path,photo_original_name,created_by)values(c.organization_id,c.branch_id,c.legacy_team_id,s.id,category,s.supplier_name_en,coalesce(supplier_ar,s.supplier_name_ar),q,unit_value,notes_value,photo_path,photo_name,actor_user_id)returning*;
exception when no_data_found or too_many_rows then raise exception'supplier receiving access denied'using errcode='42501';end$$;

revoke all on function public.create_branch_supplier_receiving(uuid,uuid,jsonb)from public,anon,authenticated;
grant execute on function public.create_branch_supplier_receiving(uuid,uuid,jsonb)to service_role;
