insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values ('maintenance-purchase-receipts','maintenance-purchase-receipts',false,5242880,array['image/jpeg','image/png','image/webp','application/pdf']) on conflict(id) do update set public=false,file_size_limit=5242880,allowed_mime_types=array['image/jpeg','image/png','image/webp','application/pdf'];

create table public.maintenance_purchase_logs (
 id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete restrict, branch_id uuid not null references public.branches(id) on delete restrict, maintenance_issue_id uuid not null references public.maintenance_issues(id) on delete restrict, maintenance_user_id uuid not null references public.profiles(id) on delete restrict, item_name text not null, quantity numeric not null check(quantity>0), amount numeric not null check(amount>=0), vendor_name text not null default 'N/A', purchase_date date not null, notes text null, payment_status text not null default 'unpaid' check(payment_status in ('unpaid','reimbursed')), reimbursement_note text null, reimbursed_at timestamptz null, receipt_storage_path text null, receipt_original_name text null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 constraint maintenance_purchase_item_check check(item_name=pg_catalog.btrim(item_name) and length(item_name) between 1 and 120), constraint maintenance_purchase_vendor_check check(vendor_name=pg_catalog.btrim(vendor_name) and length(vendor_name) between 1 and 120), constraint maintenance_purchase_notes_check check(notes is null or (notes=pg_catalog.btrim(notes) and length(notes)<=2000)), constraint maintenance_purchase_reimbursement_check check(reimbursement_note is null or (reimbursement_note=pg_catalog.btrim(reimbursement_note) and length(reimbursement_note)<=500)), constraint maintenance_purchase_receipt_path_check check(receipt_storage_path is null or receipt_storage_path ~ '^maintenance/[0-9a-fA-F-]{36}/purchases/[0-9a-fA-F-]{36}/[^/]{1,180}$')
 );
create index maintenance_purchase_issue_date_idx on public.maintenance_purchase_logs(maintenance_issue_id,purchase_date desc,created_at desc);
create trigger maintenance_purchase_logs_set_updated_at before update on public.maintenance_purchase_logs for each row execute function private.set_updated_at();
alter table public.maintenance_purchase_logs enable row level security;
revoke all on table public.maintenance_purchase_logs from public,anon,authenticated,service_role;

create or replace function private.require_maintenance_purchase_issue(actor uuid, issue uuid) returns public.maintenance_issues language plpgsql security definer set search_path=public,private as $$declare target public.maintenance_issues%rowtype;begin select i.* into target from public.maintenance_issues i where i.id=issue and private.actor_can_maintain_organization(actor,null,i.organization_id);if target.id is null then raise exception 'maintenance purchase access denied' using errcode='42501';end if;return target;end;$$;
create or replace function private.clean_purchase_text(value text, fallback text default null, max_length integer default 120) returns text language plpgsql immutable as $$declare cleaned text:=nullif(pg_catalog.regexp_replace(pg_catalog.btrim(coalesce(value,'')),'[[:space:]]+',' ','g'),'');begin if cleaned is null then return fallback;end if;if length(cleaned)>max_length then raise exception 'invalid maintenance purchase payload' using errcode='22023';end if;return cleaned;end;$$;
create or replace function public.list_maintenance_purchase_logs(actor_user_id uuid,target_issue_id uuid) returns table(id uuid,branch_id uuid,item_name text,quantity numeric,amount numeric,vendor_name text,purchase_date date,notes text,payment_status text,reimbursement_note text,reimbursed_at timestamptz,receipt_storage_path text,receipt_original_name text,created_at timestamptz,updated_at timestamptz) language plpgsql security definer set search_path=public,private as $$declare issue public.maintenance_issues%rowtype;begin issue:=private.require_maintenance_purchase_issue(actor_user_id,target_issue_id);return query select p.id,p.branch_id,p.item_name,p.quantity,p.amount,p.vendor_name,p.purchase_date,p.notes,p.payment_status,p.reimbursement_note,p.reimbursed_at,p.receipt_storage_path,p.receipt_original_name,p.created_at,p.updated_at from public.maintenance_purchase_logs p where p.maintenance_issue_id=issue.id order by p.purchase_date desc,p.created_at desc;end;$$;
create or replace function public.create_maintenance_purchase_log(actor_user_id uuid,target_issue_id uuid,payload jsonb) returns setof public.maintenance_purchase_logs language plpgsql security definer set search_path=public,private as $$declare issue public.maintenance_issues%rowtype; item text:=private.clean_purchase_text(payload->>'item_name',null,120);vendor text:=private.clean_purchase_text(payload->>'vendor_name','N/A',120);notes_value text:=private.clean_purchase_text(payload->>'notes',null,2000);path text:=private.clean_purchase_text(payload->>'receipt_storage_path',null,260);filename text:=private.clean_purchase_text(payload->>'receipt_original_name',null,180);qty numeric;cost numeric;day date;begin issue:=private.require_maintenance_purchase_issue(actor_user_id,target_issue_id);begin qty:=(payload->>'quantity')::numeric;cost:=(payload->>'amount')::numeric;day:=(payload->>'purchase_date')::date;exception when others then raise exception 'invalid maintenance purchase payload' using errcode='22023';end;if item is null or qty<=0 or cost<0 or day is null then raise exception 'invalid maintenance purchase payload' using errcode='22023';end if;return query insert into public.maintenance_purchase_logs(organization_id,branch_id,maintenance_issue_id,maintenance_user_id,item_name,quantity,amount,vendor_name,purchase_date,notes,receipt_storage_path,receipt_original_name) values(issue.organization_id,issue.branch_id,issue.id,actor_user_id,item,qty,cost,vendor,day,notes_value,path,filename) returning *;end;$$;
create or replace function public.reimburse_maintenance_purchase_log(actor_user_id uuid,target_purchase_id uuid,new_note text) returns setof public.maintenance_purchase_logs language plpgsql security definer set search_path=public,private as $$declare clean_note text:=private.clean_purchase_text(new_note,null,500);begin return query update public.maintenance_purchase_logs p set payment_status='reimbursed',reimbursement_note=clean_note,reimbursed_at=coalesce(p.reimbursed_at,now()) where p.id=target_purchase_id and p.payment_status='unpaid' and private.actor_can_maintain_organization(actor_user_id,null,p.organization_id) returning p.*;if not found then raise exception 'maintenance purchase access denied' using errcode='42501';end if;end;$$;
revoke all on function private.require_maintenance_purchase_issue(uuid,uuid) from public,anon,authenticated; grant execute on function private.require_maintenance_purchase_issue(uuid,uuid) to service_role;
revoke all on function public.list_maintenance_purchase_logs(uuid,uuid) from public,anon,authenticated; revoke all on function public.create_maintenance_purchase_log(uuid,uuid,jsonb) from public,anon,authenticated; revoke all on function public.reimburse_maintenance_purchase_log(uuid,uuid,text) from public,anon,authenticated; grant execute on function public.list_maintenance_purchase_logs(uuid,uuid) to service_role; grant execute on function public.create_maintenance_purchase_log(uuid,uuid,jsonb) to service_role; grant execute on function public.reimburse_maintenance_purchase_log(uuid,uuid,text) to service_role;
