-- Phase 2: one shared Sales/Cash report per branch and business date.
drop function if exists public.save_sales_tracking_draft(uuid,uuid,jsonb,jsonb);
drop function if exists public.submit_sales_tracking(uuid,uuid,uuid,text,jsonb,jsonb);

create or replace function public.get_sales_tracking_current_state(actor_user_id uuid,target_branch_id uuid)
returns jsonb language plpgsql security definer set search_path=''as $$declare c record;s public.sales_tracking_reports%rowtype;begin
 select*into strict c from private.phase2_branch_context(actor_user_id,target_branch_id);select*into s from public.sales_tracking_reports x where x.organization_id=c.organization_id and x.branch_id=c.branch_id and x.business_date=c.business_date;
 return pg_catalog.jsonb_build_object('report_id',s.id,'business_date',c.business_date,'state',coalesce(s.state,'draft'),'revision',coalesce(s.branch_revision,0),'submitted_at',s.submitted_at,
 'sales_rows',coalesce((select pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object('id',r.id,'entry_date',r.entry_date,'actual_cash',r.actual_cash,'actual_credit',r.actual_credit,'pos_cash',r.pos_cash,'pos_credit',r.pos_credit,'online_delivery',r.online_delivery,'remarks',r.remarks,'actual_total',r.actual_cash+r.actual_credit+r.online_delivery,'pos_total',r.pos_cash+r.pos_credit+r.online_delivery,'variance',(r.actual_cash+r.actual_credit+r.online_delivery)-(r.pos_cash+r.pos_credit+r.online_delivery))order by r.entry_date)from public.sales_tracking_sales_rows r where r.report_id=s.id),'[]'::jsonb),
 'cash_rows',coalesce((select pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object('id',r.id,'entry_date',r.entry_date,'denom_1',r.denom_1,'denom_2',r.denom_2,'denom_5',r.denom_5,'denom_10',r.denom_10,'denom_20',r.denom_20,'denom_50',r.denom_50,'denom_100',r.denom_100,'denom_200',r.denom_200,'denom_500',r.denom_500,'remaining_cash',r.remaining_cash,'remarks',r.remarks,'cash_total',r.denom_1+r.denom_2*2+r.denom_5*5+r.denom_10*10+r.denom_20*20+r.denom_50*50+r.denom_100*100+r.denom_200*200+r.denom_500*500)order by r.entry_date)from public.sales_tracking_cash_rows r where r.report_id=s.id),'[]'::jsonb));
exception when no_data_found or too_many_rows then raise exception'sales tracking state denied'using errcode='42501';end$$;

create function public.save_sales_tracking_draft(actor_user_id uuid,target_branch_id uuid,expected_revision bigint,sales_rows jsonb,cash_rows jsonb)
returns jsonb language plpgsql security definer set search_path=''as $$declare c record;s public.sales_tracking_reports%rowtype;begin
 select*into strict c from private.phase2_branch_context(actor_user_id,target_branch_id);perform private.validate_sales_tracking_sales_rows(sales_rows);perform private.validate_sales_tracking_cash_rows(cash_rows);perform private.validate_sales_tracking_entry_dates(sales_rows,c.business_date);perform private.validate_sales_tracking_entry_dates(cash_rows,c.business_date);
 perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(c.organization_id::text||':'||c.branch_id::text||':'||c.business_date::text||':sales_tracking',0));select*into s from public.sales_tracking_reports x where x.organization_id=c.organization_id and x.branch_id=c.branch_id and x.business_date=c.business_date for update;
 if(s.id is null and coalesce(expected_revision,0)<>0)or(s.id is not null and coalesce(expected_revision,-1)<>s.branch_revision)then raise exception'sales tracking changed'using errcode='40001';end if;if s.state='submitted'then raise exception'sales tracking already submitted'using errcode='23505';end if;
 if s.id is null then insert into public.sales_tracking_reports(organization_id,branch_id,supervisor_user_id,supervisor_team_id,business_date,state,branch_name_snapshot,supervisor_name_snapshot,supervisor_team_name_snapshot,branch_revision,updated_by_user_id)
  values(c.organization_id,c.branch_id,actor_user_id,c.legacy_team_id,c.business_date,'draft',c.branch_name,c.actor_name,c.actor_name||' Team',1,actor_user_id)returning*into s;
 else update public.sales_tracking_reports set branch_revision=branch_revision+1,updated_by_user_id=actor_user_id,updated_at=now()where id=s.id returning*into s;end if;
 perform private.replace_sales_tracking_rows(s.id,sales_rows,cash_rows);return public.get_sales_tracking_current_state(actor_user_id,target_branch_id);
exception when no_data_found or too_many_rows then raise exception'sales tracking draft denied'using errcode='42501';end$$;

create function public.submit_sales_tracking(actor_user_id uuid,target_branch_id uuid,expected_revision bigint,idempotency_key uuid,request_hash text,sales_rows jsonb,cash_rows jsonb)
returns jsonb language plpgsql security definer set search_path=''as $$declare c record;s public.sales_tracking_reports%rowtype;prior public.sales_tracking_submission_idempotency%rowtype;begin
 if request_hash!~'^[0-9a-f]{64}$'then raise exception'invalid sales tracking request hash'using errcode='22023';end if;select*into strict c from private.phase2_branch_context(actor_user_id,target_branch_id);perform private.validate_sales_tracking_sales_rows(sales_rows);perform private.validate_sales_tracking_cash_rows(cash_rows);perform private.validate_sales_tracking_entry_dates(sales_rows,c.business_date);perform private.validate_sales_tracking_entry_dates(cash_rows,c.business_date);if pg_catalog.jsonb_array_length(sales_rows)+pg_catalog.jsonb_array_length(cash_rows)<1 then raise exception'sales tracking submit requires rows'using errcode='22023';end if;
 select*into prior from public.sales_tracking_submission_idempotency x where x.actor_user_id=submit_sales_tracking.actor_user_id and x.idempotency_key=submit_sales_tracking.idempotency_key;if prior.actor_user_id is not null then if prior.request_hash<>request_hash then raise exception'sales tracking idempotency conflict'using errcode='23505';end if;perform 1 from public.sales_tracking_reports x where x.id=prior.report_id and x.organization_id=c.organization_id and x.branch_id=c.branch_id and x.business_date=c.business_date and x.state='submitted';if not found then raise exception'sales tracking submit denied'using errcode='42501';end if;return public.get_sales_tracking_current_state(actor_user_id,target_branch_id);end if;
 perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(c.organization_id::text||':'||c.branch_id::text||':'||c.business_date::text||':sales_tracking',0));select*into s from public.sales_tracking_reports x where x.organization_id=c.organization_id and x.branch_id=c.branch_id and x.business_date=c.business_date for update;
 if(s.id is null and coalesce(expected_revision,0)<>0)or(s.id is not null and coalesce(expected_revision,-1)<>s.branch_revision)then raise exception'sales tracking changed'using errcode='40001';end if;if s.state='submitted'then raise exception'sales tracking already submitted'using errcode='23505';end if;
 if s.id is null then insert into public.sales_tracking_reports(organization_id,branch_id,supervisor_user_id,supervisor_team_id,business_date,state,submitted_at,branch_name_snapshot,supervisor_name_snapshot,supervisor_team_name_snapshot,branch_revision,updated_by_user_id,submitted_by_user_id)
  values(c.organization_id,c.branch_id,actor_user_id,c.legacy_team_id,c.business_date,'submitted',now(),c.branch_name,c.actor_name,c.actor_name||' Team',1,actor_user_id,actor_user_id)returning*into s;
 else update public.sales_tracking_reports set state='submitted',submitted_at=now(),branch_revision=branch_revision+1,updated_by_user_id=actor_user_id,submitted_by_user_id=actor_user_id where id=s.id returning*into s;end if;
 perform private.replace_sales_tracking_rows(s.id,sales_rows,cash_rows);insert into public.sales_tracking_submission_idempotency(actor_user_id,idempotency_key,request_hash,report_id)values(actor_user_id,idempotency_key,request_hash,s.id);return public.get_sales_tracking_current_state(actor_user_id,target_branch_id);
exception when no_data_found or too_many_rows then raise exception'sales tracking submit denied'using errcode='42501';end$$;

revoke all on function public.save_sales_tracking_draft(uuid,uuid,bigint,jsonb,jsonb),public.submit_sales_tracking(uuid,uuid,bigint,uuid,text,jsonb,jsonb)from public,anon,authenticated;
grant execute on function public.save_sales_tracking_draft(uuid,uuid,bigint,jsonb,jsonb),public.submit_sales_tracking(uuid,uuid,bigint,uuid,text,jsonb,jsonb)to service_role;
