-- Keep the Phase 2 Daily Audit bodies unchanged while making the empty-array
-- initialization explicit for plpgsql_check. The idempotency argument remains
-- intentionally accepted for API compatibility; submitted-state locking is the
-- authoritative duplicate guard.
create or replace function public.save_supervisor_daily_audit_draft(actor_user_id uuid,target_branch_id uuid,target_business_date date,expected_revision bigint,auditor_kind text,auditor_id uuid,auditor_name_snapshot text,access_credential_version uuid,items jsonb)
returns jsonb language plpgsql security definer set search_path=''as $$declare c record;s public.checklist_submissions%rowtype;entry jsonb;item text;answer text;seen text[]:=array[]::text[];begin
 select*into strict c from private.phase2_branch_context(actor_user_id,target_branch_id);if auditor_kind not in('manual_access_user','organization_manager_pin')or auditor_id is null or length(btrim(auditor_name_snapshot))not between 1 and 120 or access_credential_version is null or jsonb_typeof(items)<>'array'then raise exception'invalid daily audit draft'using errcode='22023';end if;
 for entry in select value from jsonb_array_elements(items)loop item=entry->>'item_id';answer=entry->>'answer';if item is null or item not in(select d.item_id from public.daily_audit_item_definitions d where d.active)or item=any(seen)or answer not in('not_checked','compliant','non_compliant')then raise exception'invalid daily audit item'using errcode='22023';end if;seen=array_append(seen,item);end loop;
 perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(c.organization_id::text||':'||c.branch_id::text||':'||target_business_date::text||':daily_audit',0));select*into s from public.checklist_submissions x where x.organization_id=c.organization_id and x.branch_id=c.branch_id and x.business_date=target_business_date and x.checklist_type='daily_audit'for update;
 if(s.id is null and coalesce(expected_revision,0)<>0)or(s.id is not null and coalesce(expected_revision,-1)<>s.branch_revision)then raise exception'daily audit changed'using errcode='40001';end if;if s.state='submitted'then raise exception'daily audit already submitted'using errcode='55000';end if;
 if s.id is null then insert into public.checklist_submissions(organization_id,branch_id,supervisor_user_id,supervisor_team_id,business_date,checklist_type,definition_id,state,branch_name_snapshot,branch_code_snapshot,supervisor_name_snapshot,daily_audit_auditor_kind,daily_audit_auditor_id,daily_audit_auditor_name_snapshot,daily_audit_access_credential_version,branch_revision,updated_by_user_id)
  values(c.organization_id,c.branch_id,actor_user_id,c.legacy_team_id,target_business_date,'daily_audit','daily_audit_v1','draft',c.branch_name,c.branch_code,c.actor_name,auditor_kind,auditor_id,btrim(auditor_name_snapshot),access_credential_version,1,actor_user_id)returning*into s;
 else update public.checklist_submissions set updated_at=now(),daily_audit_auditor_kind=auditor_kind,daily_audit_auditor_id=auditor_id,daily_audit_auditor_name_snapshot=btrim(auditor_name_snapshot),daily_audit_access_credential_version=access_credential_version,branch_revision=branch_revision+1,updated_by_user_id=actor_user_id where id=s.id returning*into s;delete from public.daily_audit_item_results where submission_id=s.id;end if;
 insert into public.daily_audit_item_results(submission_id,organization_id,branch_id,item_id,item_number,answer,remark)select s.id,c.organization_id,c.branch_id,d.item_id,d.item_number,coalesce(x.answer,'not_checked'),btrim(coalesce(x.remark,''))from public.daily_audit_item_definitions d left join lateral(select value->>'answer'answer,value->>'remark'remark from jsonb_array_elements(items)where value->>'item_id'=d.item_id limit 1)x on true where d.active;
 return public.get_supervisor_daily_audit_current_state(actor_user_id,target_branch_id,target_business_date);
exception when no_data_found or too_many_rows then raise exception'daily audit draft denied'using errcode='42501';end$$;

create or replace function public.submit_supervisor_daily_audit(actor_user_id uuid,target_branch_id uuid,target_business_date date,expected_revision bigint,auditor_kind text,auditor_id uuid,auditor_name_snapshot text,access_credential_version uuid,items jsonb,idempotency_key text default null)
returns jsonb language plpgsql security definer set search_path=''as $$declare c record;s public.checklist_submissions%rowtype;entry jsonb;item text;answer text;remark text;seen text[]:=array[]::text[];begin
 perform idempotency_key;
 select*into strict c from private.phase2_branch_context(actor_user_id,target_branch_id);if auditor_kind not in('manual_access_user','organization_manager_pin')or auditor_id is null or length(btrim(auditor_name_snapshot))not between 1 and 120 or access_credential_version is null or jsonb_typeof(items)<>'array'or jsonb_array_length(items)<>13 then raise exception'invalid daily audit submission'using errcode='22023';end if;
 for entry in select value from jsonb_array_elements(items)loop item=entry->>'item_id';answer=entry->>'answer';remark=btrim(coalesce(entry->>'remark',''));if item is null or item not in(select d.item_id from public.daily_audit_item_definitions d where d.active)or item=any(seen)or answer not in('compliant','non_compliant')or(answer='non_compliant'and length(remark)=0)then raise exception'invalid daily audit submission'using errcode='22023';end if;seen=array_append(seen,item);end loop;
 if cardinality(seen)<>13 or exists(select 1 from public.daily_audit_item_definitions d where d.active and not(d.item_id=any(seen)))then raise exception'daily audit submission requires all items'using errcode='22023';end if;
 perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(c.organization_id::text||':'||c.branch_id::text||':'||target_business_date::text||':daily_audit',0));select*into s from public.checklist_submissions x where x.organization_id=c.organization_id and x.branch_id=c.branch_id and x.business_date=target_business_date and x.checklist_type='daily_audit'for update;
 if(s.id is null and coalesce(expected_revision,0)<>0)or(s.id is not null and coalesce(expected_revision,-1)<>s.branch_revision)then raise exception'daily audit changed'using errcode='40001';end if;if s.state='submitted'then raise exception'daily audit already submitted'using errcode='55000';end if;
 if s.id is null then insert into public.checklist_submissions(organization_id,branch_id,supervisor_user_id,supervisor_team_id,business_date,checklist_type,definition_id,state,branch_name_snapshot,branch_code_snapshot,supervisor_name_snapshot,submitted_at,daily_audit_auditor_kind,daily_audit_auditor_id,daily_audit_auditor_name_snapshot,daily_audit_access_credential_version,branch_revision,updated_by_user_id,submitted_by_user_id)
  values(c.organization_id,c.branch_id,actor_user_id,c.legacy_team_id,target_business_date,'daily_audit','daily_audit_v1','submitted',c.branch_name,c.branch_code,c.actor_name,now(),auditor_kind,auditor_id,btrim(auditor_name_snapshot),access_credential_version,1,actor_user_id,actor_user_id)returning*into s;
 else update public.checklist_submissions set state='submitted',submitted_at=now(),updated_at=now(),daily_audit_auditor_kind=auditor_kind,daily_audit_auditor_id=auditor_id,daily_audit_auditor_name_snapshot=btrim(auditor_name_snapshot),daily_audit_access_credential_version=access_credential_version,branch_revision=branch_revision+1,updated_by_user_id=actor_user_id,submitted_by_user_id=actor_user_id where id=s.id returning*into s;delete from public.daily_audit_item_results where submission_id=s.id;end if;
 insert into public.daily_audit_item_results(submission_id,organization_id,branch_id,item_id,item_number,answer,remark)select s.id,c.organization_id,c.branch_id,d.item_id,d.item_number,x.answer,btrim(coalesce(x.remark,''))from public.daily_audit_item_definitions d join lateral(select value->>'answer'answer,value->>'remark'remark from jsonb_array_elements(items)where value->>'item_id'=d.item_id limit 1)x on true where d.active;
 return public.get_supervisor_daily_audit_current_state(actor_user_id,target_branch_id,target_business_date);
exception when no_data_found or too_many_rows then raise exception'daily audit submit denied'using errcode='42501';end$$;

revoke all on function public.save_supervisor_daily_audit_draft(uuid,uuid,date,bigint,text,uuid,text,uuid,jsonb),public.submit_supervisor_daily_audit(uuid,uuid,date,bigint,text,uuid,text,uuid,jsonb,text)from public,anon,authenticated;
grant execute on function public.save_supervisor_daily_audit_draft(uuid,uuid,date,bigint,text,uuid,text,uuid,jsonb),public.submit_supervisor_daily_audit(uuid,uuid,date,bigint,text,uuid,text,uuid,jsonb,text)to service_role;
