begin;

-- A missing open-correction pointer means the active report is not a correction.
-- Normalize the derived flag at the SQL boundary so every caller receives a boolean.
create or replace function public.get_sales_tracking_current_state(actor_user_id uuid,target_branch_id uuid,target_business_date date)
returns jsonb language plpgsql security definer set search_path='' as $$
declare c record;case_row public.sales_tracking_report_cases%rowtype;active_id uuid;source_id uuid;result jsonb;
begin
 select*into strict c from private.phase2_branch_context(actor_user_id,target_branch_id);
 select x.*into case_row from public.sales_tracking_report_cases x where x.organization_id=c.organization_id and x.branch_id=c.branch_id and x.business_date=target_business_date;
 if case_row.id is null then return public.get_sales_tracking_current_state_without_corrections_legacy(actor_user_id,target_branch_id,target_business_date);end if;
 active_id:=coalesce(case_row.open_correction_report_id,case_row.authoritative_report_id,(select r.id from public.sales_tracking_reports r where r.case_id=case_row.id and r.state='draft'order by r.version_number desc limit 1));
 source_id:=case_row.authoritative_report_id;
 select pg_catalog.jsonb_build_object(
  'report_id',r.id,'business_date',r.business_date,'currency_code',r.currency_code,'state',r.state,'revision',r.branch_revision,
  'submitted_at',r.submitted_at,'submitted_by_user_id',r.submitted_by_user_id,'submitted_by_name_snapshot',r.submitted_by_name_snapshot,
  'review_status',coalesce(source.review_status,r.review_status),'review_revision',coalesce(source.review_revision,r.review_revision),'reviewed_at',coalesce(source.reviewed_at,r.reviewed_at),'reviewed_by_user_id',coalesce(source.reviewed_by_user_id,r.reviewed_by_user_id),'reviewed_by',reviewer.full_name,
  'case_id',r.case_id,'version_number',r.version_number,'is_correction_draft',coalesce(case_row.open_correction_report_id=r.id,false),'supersedes_report_id',r.supersedes_report_id,
  'attachment',private.sales_tracking_attachment_json(r.id),'attachments',private.sales_tracking_attachments_json(r.id),'source_attachments',case when r.id<>source_id then private.sales_tracking_attachments_json(source_id)else'[]'::jsonb end,
  'periods',coalesce((select pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object('id',p.id,'entry_period',p.entry_period,'entered_by_user_id',p.entered_by_user_id,'entered_by_name',p.entered_by_name_snapshot,'entered_at',p.entered_at)order by case p.entry_period when'middle_shift'then 1 else 2 end)from public.sales_tracking_period_entries p where p.report_id=r.id),'[]'::jsonb),
  'sales_rows',coalesce((select pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object('id',x.id,'entry_date',x.entry_date,'entry_period',p.entry_period,'entered_by_user_id',p.entered_by_user_id,'entered_by_name',p.entered_by_name_snapshot,'entered_at',p.entered_at,'actual_cash',x.actual_cash,'actual_credit',x.actual_credit,'pos_cash',x.pos_cash,'pos_credit',x.pos_credit,'online_delivery',x.online_delivery,'refund_total',x.refund_total,'online_amounts',private.sales_tracking_online_amounts_for_row(x.id),'remarks',x.remarks,'actual_total',x.actual_cash+x.actual_credit+x.online_delivery,'gross_sales',x.actual_cash+x.actual_credit+x.online_delivery,'net_sales',x.actual_cash+x.actual_credit+x.online_delivery-x.refund_total,'pos_total',x.pos_cash+x.pos_credit+x.online_delivery,'variance',(x.actual_cash+x.actual_credit)-(x.pos_cash+x.pos_credit))order by case p.entry_period when'middle_shift'then 1 else 2 end)from public.sales_tracking_sales_rows x left join public.sales_tracking_period_entries p on p.id=x.period_entry_id where x.report_id=r.id),'[]'::jsonb),
  'cash_rows',coalesce((select pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object('id',x.id,'entry_date',x.entry_date,'entry_period',p.entry_period,'entered_by_user_id',p.entered_by_user_id,'entered_by_name',p.entered_by_name_snapshot,'entered_at',p.entered_at,'denom_1',x.denom_1,'denom_2',x.denom_2,'denom_5',x.denom_5,'denom_10',x.denom_10,'denom_20',x.denom_20,'denom_50',x.denom_50,'denom_100',x.denom_100,'denom_200',x.denom_200,'denom_500',x.denom_500,'remaining_cash',x.remaining_cash,'remarks',x.remarks,'cash_total',x.denom_1+x.denom_2*2+x.denom_5*5+x.denom_10*10+x.denom_20*20+x.denom_50*50+x.denom_100*100+x.denom_200*200+x.denom_500*500)order by case p.entry_period when'middle_shift'then 1 else 2 end)from public.sales_tracking_cash_rows x left join public.sales_tracking_period_entries p on p.id=x.period_entry_id where x.report_id=r.id),'[]'::jsonb),
  'totals',pg_catalog.jsonb_build_object('actual_cash',coalesce((select sum(x.actual_cash)from public.sales_tracking_sales_rows x where x.report_id=r.id),0),'actual_credit',coalesce((select sum(x.actual_credit)from public.sales_tracking_sales_rows x where x.report_id=r.id),0),'pos_cash',coalesce((select sum(x.pos_cash)from public.sales_tracking_sales_rows x where x.report_id=r.id),0),'pos_credit',coalesce((select sum(x.pos_credit)from public.sales_tracking_sales_rows x where x.report_id=r.id),0),'online_delivery',coalesce((select sum(x.online_delivery)from public.sales_tracking_sales_rows x where x.report_id=r.id),0),'actual_total',coalesce((select sum(x.actual_cash+x.actual_credit+x.online_delivery)from public.sales_tracking_sales_rows x where x.report_id=r.id),0),'gross_sales',coalesce((select sum(x.actual_cash+x.actual_credit+x.online_delivery)from public.sales_tracking_sales_rows x where x.report_id=r.id),0),'refund_total',coalesce((select sum(x.refund_total)from public.sales_tracking_sales_rows x where x.report_id=r.id),0),'net_sales',coalesce((select sum(x.actual_cash+x.actual_credit+x.online_delivery-x.refund_total)from public.sales_tracking_sales_rows x where x.report_id=r.id),0),'pos_total',coalesce((select sum(x.pos_cash+x.pos_credit+x.online_delivery)from public.sales_tracking_sales_rows x where x.report_id=r.id),0),'variance',coalesce((select sum((x.actual_cash+x.actual_credit)-(x.pos_cash+x.pos_credit))from public.sales_tracking_sales_rows x where x.report_id=r.id),0),'cash_total',coalesce((select sum(x.denom_1+x.denom_2*2+x.denom_5*5+x.denom_10*10+x.denom_20*20+x.denom_50*50+x.denom_100*100+x.denom_200*200+x.denom_500*500)from public.sales_tracking_cash_rows x where x.report_id=r.id),0),'remaining_cash',coalesce((select sum(x.remaining_cash)from public.sales_tracking_cash_rows x where x.report_id=r.id),0))
 )into result from public.sales_tracking_reports r left join public.sales_tracking_reports source on source.id=source_id left join public.profiles reviewer on reviewer.id=coalesce(source.reviewed_by_user_id,r.reviewed_by_user_id)where r.id=active_id;
 return result;
exception when no_data_found or too_many_rows then raise exception'sales tracking state denied'using errcode='42501';end$$;

revoke all on function public.get_sales_tracking_current_state(uuid,uuid,date)from public,anon,authenticated;
grant execute on function public.get_sales_tracking_current_state(uuid,uuid,date)to service_role;

commit;
