-- Keep generic report readers from showing the authenticated runtime actor for
-- Daily Audit submissions. Daily Audit already stores the immutable access-user
-- snapshot in checklist_submissions.daily_audit_auditor_name_snapshot.

create or replace function public.get_phase4a_report_detail(actor_user_id uuid,target_report_id uuid,manager_mode boolean default false)
returns jsonb language plpgsql security definer set search_path=''as $$declare s public.checklist_submissions%rowtype;begin
 select*into strict s from public.checklist_submissions x where x.id=target_report_id and x.state='submitted';
 if(manager_mode and not private.actor_manages_active_organization(actor_user_id,s.organization_id))or(not manager_mode and not(
  (s.checklist_type='staff_hygiene'and private.actor_can_read_operational_branch(actor_user_id,s.branch_id))
  or(s.checklist_type<>'staff_hygiene'and s.supervisor_user_id=actor_user_id and exists(select 1 from public.profiles p where p.id=actor_user_id and p.disabled_at is null and not p.must_change_password))
 ))then raise exception'report access denied'using errcode='42501';end if;
 return pg_catalog.jsonb_build_object('id',s.id,'organization_id',s.organization_id,'branch_id',s.branch_id,'branch_name',s.branch_name_snapshot,'branch_code',s.branch_code_snapshot,'supervisor_team_id',s.supervisor_team_id,'operational_team_id',s.operational_team_id,'operational_team_name',s.operational_team_name_snapshot,'business_date',s.business_date,'checklist_type',s.checklist_type,'definition_id',s.definition_id,'submitted_at',s.submitted_at,
  'submitted_by',case when s.checklist_type='daily_audit'then coalesce(nullif(btrim(s.daily_audit_auditor_name_snapshot),''),nullif(btrim(s.supervisor_name_snapshot),''))else s.supervisor_name_snapshot end,
  'completion',100,'status',case when exists(select 1 from public.checklist_issues i where i.source_submission_id=s.id)then'issues_found'else'compliant'end,'issue_count',(select count(*)from public.checklist_issues i where i.source_submission_id=s.id),
  'items',coalesce((select pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object('item_id',r.item_id,'item_text',r.item_text_snapshot,'answer',r.answer,'remark',r.remark,'evidence',(select pg_catalog.jsonb_build_object('id',e.id,'status',e.status,'mime_type',e.mime_type,'byte_size',e.byte_size,'available',true)from public.checklist_issue_evidence e where e.final_result_id=r.id and e.status='finalized'limit 1))order by r.ordinal)from public.opening_item_results r where r.submission_id=s.id),'[]'::jsonb),
  'staff',coalesce((select pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object('staff_id',h.operational_staff_id,'display_name',h.display_name_snapshot,'operational_roles',h.operational_roles_snapshot,'uniform',h.uniform_result,'fingernails',h.fingernails_result,'hair',h.hair_result,'facial_hair',h.facial_hair_result,'remark',h.remark)order by h.display_name_snapshot,h.id)from public.hygiene_staff_snapshots h where h.submission_id=s.id),'[]'::jsonb));
exception when no_data_found or too_many_rows then raise exception'report access denied'using errcode='42501';end$$;

create or replace function public.list_phase2_branch_reports(actor_user_id uuid,target_branch_id uuid,requested_page int default 1,requested_page_size int default 20,target_checklist_type text default null)
returns jsonb language plpgsql stable security definer set search_path=''as $$declare c record;begin
 select*into strict c from private.phase2_branch_context(actor_user_id,target_branch_id);
 if requested_page<1 or requested_page_size not between 1 and 50 or(target_checklist_type is not null and target_checklist_type not in('kitchen_opening','foh_opening','staff_hygiene','oil_tracking','cold_storage','sales_tracking','daily_audit','purchase_log','supplier_receiving'))then raise exception'invalid report list'using errcode='22023';end if;
 return(select pg_catalog.jsonb_build_object('reports',coalesce(pg_catalog.jsonb_agg(x.dto order by x.business_date desc,x.submitted_at desc,x.id desc)filter(where x.rn between(requested_page-1)*requested_page_size+1 and requested_page*requested_page_size),'[]'::jsonb),'page',requested_page,'page_size',requested_page_size,'total',count(*))from(
  select q.*,row_number()over(order by q.business_date desc,q.submitted_at desc,q.id desc)rn from(
   select s.id,s.business_date,s.submitted_at,s.checklist_type,pg_catalog.jsonb_build_object('id',s.id,'branch_id',s.branch_id,'checklist_type',s.checklist_type,'business_date',s.business_date,'submitted_at',s.submitted_at,'submitted_by',case when s.checklist_type='daily_audit'then coalesce(nullif(btrim(s.daily_audit_auditor_name_snapshot),''),nullif(btrim(s.supervisor_name_snapshot),''))else coalesce(p.full_name,s.supervisor_name_snapshot)end,'completion',100,'issue_count',case when s.checklist_type='daily_audit'then(select count(*)from public.daily_audit_item_results r where r.submission_id=s.id and r.answer='non_compliant')else(select count(*)from public.checklist_issues i where i.source_submission_id=s.id)end,'status',case when s.checklist_type='daily_audit'and exists(select 1 from public.daily_audit_item_results r where r.submission_id=s.id and r.answer='non_compliant')then'issues_found'when s.checklist_type<>'daily_audit'and exists(select 1 from public.checklist_issues i where i.source_submission_id=s.id)then'issues_found'else'compliant'end)dto
   from public.checklist_submissions s left join public.profiles p on p.id=coalesce(s.submitted_by_user_id,s.supervisor_user_id)
   where s.organization_id=c.organization_id and s.branch_id=c.branch_id and s.state='submitted'and s.checklist_type in('kitchen_opening','foh_opening','staff_hygiene','daily_audit')
   union all
   select s.id,s.business_date,greatest(coalesce(s.opening_submitted_at,'-infinity'::timestamptz),coalesce(s.closing_submitted_at,'-infinity'::timestamptz)),'oil_tracking',pg_catalog.jsonb_build_object('id',s.id,'branch_id',s.branch_id,'checklist_type','oil_tracking','business_date',s.business_date,'submitted_at',greatest(coalesce(s.opening_submitted_at,'-infinity'::timestamptz),coalesce(s.closing_submitted_at,'-infinity'::timestamptz)),'submitted_by',coalesce(p.full_name,s.supervisor_name_snapshot),'completion',case when s.opening_submitted_at is not null and s.closing_submitted_at is not null then 100 else 50 end,'issue_count',(select count(*)from public.oil_tracking_issues i where i.source_submission_id=s.id),'status',case when s.opening_submitted_at is null or s.closing_submitted_at is null then'in_progress'when exists(select 1 from public.oil_tracking_issues i where i.source_submission_id=s.id)then'issues_found'else'compliant'end)
   from public.oil_tracking_submissions s left join public.profiles p on p.id=coalesce(s.closing_submitted_by_user_id,s.opening_submitted_by_user_id,s.supervisor_user_id)where s.organization_id=c.organization_id and s.branch_id=c.branch_id and(s.opening_submitted_at is not null or s.closing_submitted_at is not null)
   union all
   select s.id,s.business_date,max(r.submitted_at),'cold_storage',pg_catalog.jsonb_build_object('id',s.id,'branch_id',s.branch_id,'checklist_type','cold_storage','business_date',s.business_date,'submitted_at',max(r.submitted_at),'submitted_by',coalesce(max(p.full_name),s.supervisor_name_snapshot),'completion',100,'issue_count',(select count(*)from public.cold_storage_issues i where i.submission_id=s.id),'status',case when exists(select 1 from public.cold_storage_issues i where i.submission_id=s.id)then'issues_found'else'compliant'end)
   from public.cold_storage_submissions s join public.cold_storage_readings r on r.submission_id=s.id and r.submitted_at is not null left join public.profiles p on p.id=r.submitted_by_user_id where s.organization_id=c.organization_id and s.branch_id=c.branch_id group by s.id
   union all
   select s.id,s.business_date,s.submitted_at,'sales_tracking',pg_catalog.jsonb_build_object('id',s.id,'branch_id',s.branch_id,'checklist_type','sales_tracking','business_date',s.business_date,'submitted_at',s.submitted_at,'submitted_by',coalesce(p.full_name,s.supervisor_name_snapshot),'completion',100,'issue_count',0,'status','compliant')from public.sales_tracking_reports s left join public.profiles p on p.id=coalesce(s.submitted_by_user_id,s.supervisor_user_id)where s.organization_id=c.organization_id and s.branch_id=c.branch_id and s.state='submitted'
   union all
   select r.id,r.purchase_date,r.created_at,'purchase_log',pg_catalog.jsonb_build_object('id',r.id,'branch_id',r.branch_id,'checklist_type','purchase_log','business_date',r.purchase_date,'submitted_at',r.created_at,'submitted_by',p.full_name,'completion',100,'issue_count',0,'status','recorded')from public.branch_purchase_logs r left join public.profiles p on p.id=r.created_by where r.organization_id=c.organization_id and r.branch_id=c.branch_id
   union all
   select r.id,(r.created_at at time zone b.timezone)::date,r.created_at,'supplier_receiving',pg_catalog.jsonb_build_object('id',r.id,'branch_id',r.branch_id,'checklist_type','supplier_receiving','business_date',(r.created_at at time zone b.timezone)::date,'submitted_at',r.created_at,'submitted_by',p.full_name,'completion',100,'issue_count',0,'status','recorded')from public.branch_supplier_receivings r join public.branches b on b.id=r.branch_id left join public.profiles p on p.id=r.created_by where r.organization_id=c.organization_id and r.branch_id=c.branch_id
  )q where target_checklist_type is null or q.checklist_type=target_checklist_type
 )x);
exception when no_data_found or too_many_rows then raise exception'report access denied'using errcode='42501';end$$;

create or replace function public.get_phase2_branch_report_detail_core(actor_user_id uuid,target_report_id uuid)
returns jsonb language plpgsql stable security definer set search_path=''as $$declare result jsonb;branch uuid;begin
 select x.branch_id into branch from(select id,branch_id from public.checklist_submissions union all select id,branch_id from public.oil_tracking_submissions union all select id,branch_id from public.cold_storage_submissions union all select id,branch_id from public.sales_tracking_reports)x where x.id=target_report_id;
 if branch is null or not private.actor_can_read_operational_branch(actor_user_id,branch)then raise exception'report access denied'using errcode='42501';end if;
 select pg_catalog.jsonb_build_object('id',s.id,'branch_id',s.branch_id,'branch_name',s.branch_name_snapshot,'business_date',s.business_date,'checklist_type',s.checklist_type,'definition_id',s.definition_id,'submitted_at',s.submitted_at,'submitted_by',case when s.checklist_type='daily_audit'then coalesce(nullif(btrim(s.daily_audit_auditor_name_snapshot),''),nullif(btrim(s.supervisor_name_snapshot),''))else coalesce(p.full_name,s.supervisor_name_snapshot)end,'completion',100,'issue_count',case when s.checklist_type='daily_audit'then(select count(*)from public.daily_audit_item_results r where r.submission_id=s.id and r.answer='non_compliant')else(select count(*)from public.checklist_issues i where i.source_submission_id=s.id)end,'status',case when(s.checklist_type='daily_audit'and exists(select 1 from public.daily_audit_item_results r where r.submission_id=s.id and r.answer='non_compliant'))or(s.checklist_type<>'daily_audit'and exists(select 1 from public.checklist_issues i where i.source_submission_id=s.id))then'issues_found'else'compliant'end,
  'items',case when s.checklist_type='daily_audit'then coalesce((select pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object('item_id',r.item_id,'item_text',d.item_label_en,'answer',r.answer,'remark',r.remark)order by r.item_number)from public.daily_audit_item_results r join public.daily_audit_item_definitions d on d.item_id=r.item_id where r.submission_id=s.id),'[]'::jsonb)else coalesce((select pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object('item_id',r.item_id,'item_text',r.item_text_snapshot,'answer',r.answer,'remark',r.remark)order by r.ordinal)from public.opening_item_results r where r.submission_id=s.id),'[]'::jsonb)end,
  'staff',coalesce((select pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object('staff_id',h.operational_staff_id,'display_name',h.display_name_snapshot,'operational_roles',h.operational_roles_snapshot,'uniform',h.uniform_result,'fingernails',h.fingernails_result,'hair',h.hair_result,'facial_hair',h.facial_hair_result,'remark',h.remark)order by h.display_name_snapshot)from public.hygiene_staff_snapshots h where h.submission_id=s.id),'[]'::jsonb))into result from public.checklist_submissions s left join public.profiles p on p.id=coalesce(s.submitted_by_user_id,s.supervisor_user_id)where s.id=target_report_id and s.state='submitted';
 if result is not null then return result;end if;
 select pg_catalog.jsonb_build_object('id',s.id,'branch_id',s.branch_id,'branch_name',s.branch_name_snapshot,'business_date',s.business_date,'checklist_type','oil_tracking','definition_id','oil_tracking_v1','submitted_at',greatest(coalesce(s.opening_submitted_at,'-infinity'::timestamptz),coalesce(s.closing_submitted_at,'-infinity'::timestamptz)),'submitted_by',coalesce(p.full_name,s.supervisor_name_snapshot),'completion',case when s.opening_submitted_at is not null and s.closing_submitted_at is not null then 100 else 50 end,'issue_count',(select count(*)from public.oil_tracking_issues i where i.source_submission_id=s.id),'status',case when exists(select 1 from public.oil_tracking_issues i where i.source_submission_id=s.id)then'issues_found'else'compliant'end,'items',coalesce((select pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object('item_id',r.fryer_id,'item_text',r.fryer_label_snapshot,'answer',r.opening_status,'remark',r.opening_note||case when r.closing_note=''then''else' / '||r.closing_note end)order by r.fryer_id)from public.oil_tracking_fryer_results r where r.submission_id=s.id),'[]'::jsonb))into result from public.oil_tracking_submissions s left join public.profiles p on p.id=coalesce(s.closing_submitted_by_user_id,s.opening_submitted_by_user_id,s.supervisor_user_id)where s.id=target_report_id and(s.opening_submitted_at is not null or s.closing_submitted_at is not null);if result is not null then return result;end if;
 select pg_catalog.jsonb_build_object('id',s.id,'branch_id',s.branch_id,'branch_name',s.branch_name_snapshot,'business_date',s.business_date,'checklist_type','cold_storage','definition_id','cold_storage_v1','submitted_at',max(r.submitted_at),'submitted_by',coalesce(max(p.full_name),s.supervisor_name_snapshot),'completion',100,'issue_count',(select count(*)from public.cold_storage_issues i where i.submission_id=s.id),'status',case when exists(select 1 from public.cold_storage_issues i where i.submission_id=s.id)then'issues_found'else'compliant'end,'items',pg_catalog.jsonb_agg(pg_catalog.jsonb_build_object('item_id',r.equipment_id||':'||r.slot,'item_text',e.equipment_name||' — '||r.slot,'answer',r.status,'remark',r.corrective_action)order by r.slot,r.equipment_id))into result from public.cold_storage_submissions s join public.cold_storage_readings r on r.submission_id=s.id and r.submitted_at is not null join public.cold_storage_equipment e on e.submission_id=s.id and e.equipment_id=r.equipment_id left join public.profiles p on p.id=r.submitted_by_user_id where s.id=target_report_id group by s.id;if result is not null then return result;end if;
 select pg_catalog.jsonb_build_object('id',s.id,'branch_id',s.branch_id,'branch_name',s.branch_name_snapshot,'business_date',s.business_date,'checklist_type','sales_tracking','definition_id','sales_tracking_v1','submitted_at',s.submitted_at,'submitted_by',coalesce(p.full_name,s.supervisor_name_snapshot),'completion',100,'issue_count',0,'status','compliant','items',coalesce((select pg_catalog.jsonb_agg(x.item order by x.entry_date,x.kind)from(select r.entry_date,'sales'kind,pg_catalog.jsonb_build_object('item_id','sales:'||r.id,'item_text','Sales — '||r.entry_date,'answer','recorded','remark',coalesce(r.remarks,''))item from public.sales_tracking_sales_rows r where r.report_id=s.id union all select r.entry_date,'cash',pg_catalog.jsonb_build_object('item_id','cash:'||r.id,'item_text','Cash — '||r.entry_date,'answer','recorded','remark',coalesce(r.remarks,''))from public.sales_tracking_cash_rows r where r.report_id=s.id)x),'[]'::jsonb))into result from public.sales_tracking_reports s left join public.profiles p on p.id=coalesce(s.submitted_by_user_id,s.supervisor_user_id)where s.id=target_report_id and s.state='submitted';if result is not null then return result;end if;
 raise exception'report access denied'using errcode='42501';end$$;

revoke all on function public.get_phase4a_report_detail(uuid,uuid,boolean),public.list_phase2_branch_reports(uuid,uuid,int,int,text),public.get_phase2_branch_report_detail_core(uuid,uuid)from public,anon,authenticated;
grant execute on function public.get_phase4a_report_detail(uuid,uuid,boolean),public.list_phase2_branch_reports(uuid,uuid,int,int,text),public.get_phase2_branch_report_detail_core(uuid,uuid)to service_role;
