-- Phase 2: Purchase Log, supplier master, and Supplier Receiving are branch-shared collections.
create or replace function public.list_branch_purchase_logs(actor_user_id uuid,target_branch_id uuid)
returns table(id uuid,branch_id uuid,branch_name text,category text,item_name text,quantity numeric,amount numeric,vendor_name text,purchase_date date,notes text,payment_status text,reimbursement_note text,reimbursed_at timestamptz,reimbursed_by uuid,invoice_storage_path text,invoice_original_name text,created_by uuid,created_at timestamptz,updated_at timestamptz)
language plpgsql security definer set search_path=''as $$declare c record;begin
 select*into strict c from private.phase2_branch_context(actor_user_id,target_branch_id);
 return query select l.id,l.branch_id,b.name,l.category,l.item_name,l.quantity,l.amount,l.vendor_name,l.purchase_date,l.notes,l.payment_status,l.reimbursement_note,l.reimbursed_at,l.reimbursed_by,l.invoice_storage_path,l.invoice_original_name,l.created_by,l.created_at,l.updated_at from public.branch_purchase_logs l join public.branches b on b.id=l.branch_id where l.organization_id=c.organization_id and l.branch_id=c.branch_id order by l.purchase_date desc,l.created_at desc;
exception when no_data_found or too_many_rows then raise exception'purchase log access denied'using errcode='42501';end$$;

create or replace function public.create_branch_purchase_log(actor_user_id uuid,target_branch_id uuid,payload jsonb)
returns setof public.branch_purchase_logs language plpgsql security definer set search_path=''as $$declare c record;clean_category text:=payload->>'category';clean_item text:=private.clean_purchase_text(payload->>'item_name',null,120);clean_vendor text:=private.clean_purchase_text(payload->>'vendor_name','N/A',120);clean_notes text:=private.clean_purchase_text(payload->>'notes',null,2000);clean_status text:=coalesce(nullif(payload->>'payment_status',''),'unpaid');clean_note text:=private.clean_purchase_text(payload->>'reimbursement_note',null,500);clean_path text:=private.clean_purchase_text(payload->>'invoice_storage_path',null,260);clean_name text:=private.clean_purchase_text(payload->>'invoice_original_name',null,180);q numeric;a numeric;d date;begin
 select*into strict c from private.phase2_branch_context(actor_user_id,target_branch_id);if clean_category not in('stationery','kitchen','equipment')or clean_status not in('unpaid','reimbursed')then raise exception'invalid purchase log payload'using errcode='22023';end if;
 begin q:=(payload->>'quantity')::numeric;a:=(payload->>'amount')::numeric;d:=(payload->>'purchase_date')::date;exception when others then raise exception'invalid purchase log payload'using errcode='22023';end;if q<=0 or a<0 or d is null then raise exception'invalid purchase log payload'using errcode='22023';end if;
 return query insert into public.branch_purchase_logs(organization_id,branch_id,supervisor_team_id,category,item_name,quantity,amount,vendor_name,purchase_date,notes,payment_status,reimbursement_note,reimbursed_at,reimbursed_by,invoice_storage_path,invoice_original_name,created_by)
 values(c.organization_id,c.branch_id,c.legacy_team_id,clean_category,clean_item,q,a,clean_vendor,d,clean_notes,clean_status,clean_note,case when clean_status='reimbursed'then now()end,case when clean_status='reimbursed'then actor_user_id end,clean_path,clean_name,actor_user_id)returning*;
exception when no_data_found or too_many_rows then raise exception'purchase log access denied'using errcode='42501';end$$;

create or replace function public.update_branch_purchase_log_payment_status(actor_user_id uuid,target_branch_id uuid,target_purchase_log_id uuid,new_payment_status text,new_reimbursement_note text)
returns setof public.branch_purchase_logs language plpgsql security definer set search_path=''as $$declare c record;clean_status text:=coalesce(nullif(new_payment_status,''),'unpaid');clean_note text:=private.clean_purchase_text(new_reimbursement_note,null,500);begin
 select*into strict c from private.phase2_branch_context(actor_user_id,target_branch_id);if clean_status not in('unpaid','reimbursed')then raise exception'invalid purchase status'using errcode='22023';end if;
 return query update public.branch_purchase_logs l set payment_status=clean_status,reimbursement_note=clean_note,reimbursed_at=case when clean_status='reimbursed'then coalesce(l.reimbursed_at,now())else null end,reimbursed_by=case when clean_status='reimbursed'then coalesce(l.reimbursed_by,actor_user_id)else null end where l.id=target_purchase_log_id and l.organization_id=c.organization_id and l.branch_id=c.branch_id returning l.*;if not found then raise exception'purchase log access denied'using errcode='42501';end if;
exception when no_data_found or too_many_rows then raise exception'purchase log access denied'using errcode='42501';end$$;

create function private.upsert_branch_supplier_for_branch(target_organization_id uuid,target_branch_id uuid,target_legacy_team_id uuid,actor_user_id uuid,clean_supplier_en text,clean_supplier_ar text)
returns public.branch_suppliers language plpgsql security definer set search_path=''as $$declare s public.branch_suppliers%rowtype;begin
 if clean_supplier_en is null then raise exception'invalid supplier payload'using errcode='22023';end if;
 insert into public.branch_suppliers(organization_id,branch_id,supervisor_team_id,supplier_name_en,supplier_name_ar,created_by)values(target_organization_id,target_branch_id,target_legacy_team_id,clean_supplier_en,clean_supplier_ar,actor_user_id)on conflict do nothing returning*into s;
 if s.id is null then select*into s from public.branch_suppliers x where x.organization_id=target_organization_id and x.branch_id=target_branch_id and lower(btrim(x.supplier_name_en))=lower(btrim(clean_supplier_en));if s.id is null then raise exception'invalid supplier payload'using errcode='22023';end if;if s.supplier_name_ar is null and clean_supplier_ar is not null then update public.branch_suppliers set supplier_name_ar=clean_supplier_ar where id=s.id returning*into s;end if;end if;return s;
end$$;

create or replace function public.list_branch_suppliers(actor_user_id uuid,target_branch_id uuid)
returns table(id uuid,branch_id uuid,supplier_name_en text,supplier_name_ar text,created_at timestamptz,updated_at timestamptz)
language plpgsql security definer set search_path=''as $$declare c record;begin select*into strict c from private.phase2_branch_context(actor_user_id,target_branch_id);return query select s.id,s.branch_id,s.supplier_name_en,s.supplier_name_ar,s.created_at,s.updated_at from public.branch_suppliers s where s.organization_id=c.organization_id and s.branch_id=c.branch_id order by s.supplier_name_en,s.created_at;exception when no_data_found or too_many_rows then raise exception'supplier access denied'using errcode='42501';end$$;

create or replace function public.create_branch_supplier(actor_user_id uuid,target_branch_id uuid,payload jsonb)
returns setof public.branch_suppliers language plpgsql security definer set search_path=''as $$declare c record;s public.branch_suppliers%rowtype;begin select*into strict c from private.phase2_branch_context(actor_user_id,target_branch_id);s:=private.upsert_branch_supplier_for_branch(c.organization_id,c.branch_id,c.legacy_team_id,actor_user_id,private.clean_supplier_receiving_text(payload->>'supplier_name_en',null,120),private.clean_supplier_receiving_text(payload->>'supplier_name_ar',null,120));return query select s.*;exception when no_data_found or too_many_rows then raise exception'supplier access denied'using errcode='42501';end$$;

create or replace function public.list_branch_supplier_receivings(actor_user_id uuid,target_branch_id uuid)
returns table(id uuid,branch_id uuid,branch_name text,supplier_id uuid,category text,supplier_name_en text,supplier_name_ar text,quantity numeric,unit text,notes text,photo_storage_path text,photo_original_name text,created_by uuid,created_at timestamptz,updated_at timestamptz)
language plpgsql security definer set search_path=''as $$declare c record;begin select*into strict c from private.phase2_branch_context(actor_user_id,target_branch_id);return query select r.id,r.branch_id,b.name,r.supplier_id,r.category,r.supplier_name_en,r.supplier_name_ar,r.quantity,r.unit,r.notes,r.photo_storage_path,r.photo_original_name,r.created_by,r.created_at,r.updated_at from public.branch_supplier_receivings r join public.branches b on b.id=r.branch_id where r.organization_id=c.organization_id and r.branch_id=c.branch_id order by r.created_at desc;exception when no_data_found or too_many_rows then raise exception'supplier receiving access denied'using errcode='42501';end$$;

create or replace function public.create_branch_supplier_receiving(actor_user_id uuid,target_branch_id uuid,payload jsonb)
returns setof public.branch_supplier_receivings language plpgsql security definer set search_path=''as $$declare c record;s public.branch_suppliers%rowtype;category text:=payload->>'category';supplier_en text:=private.clean_supplier_receiving_text(payload->>'supplier_name_en',null,120);supplier_ar text:=private.clean_supplier_receiving_text(payload->>'supplier_name_ar',null,120);unit_value text:=private.clean_supplier_receiving_text(payload->>'unit',null,40);notes_value text:=private.clean_supplier_receiving_text(payload->>'notes',null,2000);photo_path text:=private.clean_supplier_receiving_text(payload->>'photo_storage_path',null,260);photo_name text:=private.clean_supplier_receiving_text(payload->>'photo_original_name',null,180);supplier_uuid uuid;q numeric;begin
 select*into strict c from private.phase2_branch_context(actor_user_id,target_branch_id);if category not in('raw','frozen','juice')or unit_value is null then raise exception'invalid supplier receiving payload'using errcode='22023';end if;begin q:=(payload->>'quantity')::numeric;supplier_uuid:=nullif(payload->>'supplier_id','')::uuid;exception when others then raise exception'invalid supplier receiving payload'using errcode='22023';end;if q<=0 then raise exception'invalid supplier receiving payload'using errcode='22023';end if;
 if supplier_uuid is not null then select*into s from public.branch_suppliers x where x.id=supplier_uuid and x.organization_id=c.organization_id and x.branch_id=c.branch_id;if s.id is null then raise exception'supplier receiving access denied'using errcode='42501';end if;if s.supplier_name_ar is null and supplier_ar is not null then update public.branch_suppliers set supplier_name_ar=supplier_ar where id=s.id returning*into s;end if;else s:=private.upsert_branch_supplier_for_branch(c.organization_id,c.branch_id,c.legacy_team_id,actor_user_id,supplier_en,supplier_ar);end if;
 return query insert into public.branch_supplier_receivings(organization_id,branch_id,supervisor_team_id,supplier_id,category,supplier_name_en,supplier_name_ar,quantity,unit,notes,photo_storage_path,photo_original_name,created_by)values(c.organization_id,c.branch_id,c.legacy_team_id,s.id,category,s.supplier_name_en,coalesce(supplier_ar,s.supplier_name_ar),q,unit_value,notes_value,photo_path,photo_name,actor_user_id)returning*;
exception when no_data_found or too_many_rows then raise exception'supplier receiving access denied'using errcode='42501';end$$;

revoke all on function private.upsert_branch_supplier_for_branch(uuid,uuid,uuid,uuid,text,text)from public,anon,authenticated;
grant execute on function private.upsert_branch_supplier_for_branch(uuid,uuid,uuid,uuid,text,text)to service_role;
