-- Include the branch-owned Purchase Log and Supplier Receiving records in the
-- same Supervisor submission-history namespace as the migrated checklists.
create or replace function public.list_phase2_branch_reports(actor_user_id uuid,target_branch_id uuid,requested_page int default 1,requested_page_size int default 20,target_checklist_type text default null)
returns jsonb language plpgsql stable security definer set search_path=''as $$declare c record;begin
 select*into strict c from private.phase2_branch_context(actor_user_id,target_branch_id);
 if requested_page<1 or requested_page_size not between 1 and 50 or(target_checklist_type is not null and target_checklist_type not in('kitchen_opening','foh_opening','staff_hygiene','oil_tracking','cold_storage','sales_tracking','daily_audit','purchase_log','supplier_receiving'))then raise exception'invalid report list'using errcode='22023';end if;
 return(select pg_catalog.jsonb_build_object('reports',coalesce(pg_catalog.jsonb_agg(x.dto order by x.business_date desc,x.submitted_at desc,x.id desc)filter(where x.rn between(requested_page-1)*requested_page_size+1 and requested_page*requested_page_size),'[]'::jsonb),'page',requested_page,'page_size',requested_page_size,'total',count(*))from(
  select q.*,row_number()over(order by q.business_date desc,q.submitted_at desc,q.id desc)rn from(
   select s.id,s.business_date,s.submitted_at,s.checklist_type,pg_catalog.jsonb_build_object('id',s.id,'branch_id',s.branch_id,'checklist_type',s.checklist_type,'business_date',s.business_date,'submitted_at',s.submitted_at,'submitted_by',coalesce(p.full_name,s.supervisor_name_snapshot),'completion',100,'issue_count',case when s.checklist_type='daily_audit'then(select count(*)from public.daily_audit_item_results r where r.submission_id=s.id and r.answer='non_compliant')else(select count(*)from public.checklist_issues i where i.source_submission_id=s.id)end,'status',case when s.checklist_type='daily_audit'and exists(select 1 from public.daily_audit_item_results r where r.submission_id=s.id and r.answer='non_compliant')then'issues_found'when s.checklist_type<>'daily_audit'and exists(select 1 from public.checklist_issues i where i.source_submission_id=s.id)then'issues_found'else'compliant'end)dto
   from public.checklist_submissions s left join public.profiles p on p.id=coalesce(s.submitted_by_user_id,s.supervisor_user_id)
   where s.organization_id=c.organization_id and s.branch_id=c.branch_id and s.state='submitted'and s.checklist_type in('kitchen_opening','foh_opening','staff_hygiene','daily_audit')
   union all
   select s.id,s.business_date,greatest(coalesce(s.opening_submitted_at,'-infinity'::timestamptz),coalesce(s.closing_submitted_at,'-infinity'::timestamptz)),'oil_tracking',pg_catalog.jsonb_build_object('id',s.id,'branch_id',s.branch_id,'checklist_type','oil_tracking','business_date',s.business_date,'submitted_at',greatest(coalesce(s.opening_submitted_at,'-infinity'::timestamptz),coalesce(s.closing_submitted_at,'-infinity'::timestamptz)),'submitted_by',coalesce(p.full_name,s.supervisor_name_snapshot),'completion',case when s.opening_submitted_at is not null and s.closing_submitted_at is not null then 100 else 50 end,'issue_count',(select count(*)from public.oil_tracking_issues i where i.source_submission_id=s.id),'status',case when s.opening_submitted_at is null or s.closing_submitted_at is null then'in_progress'when exists(select 1 from public.oil_tracking_issues i where i.source_submission_id=s.id)then'issues_found'else'compliant'end)
   from public.oil_tracking_submissions s left join public.profiles p on p.id=coalesce(s.closing_submitted_by_user_id,s.opening_submitted_by_user_id,s.supervisor_user_id)where s.organization_id=c.organization_id and s.branch_id=c.branch_id and(s.opening_submitted_at is not null or s.closing_submitted_at is not null)
   union all
   select s.id,s.business_date,max(r.submitted_at),'cold_storage',pg_catalog.jsonb_build_object('id',s.id,'branch_id',s.branch_id,'checklist_type','cold_storage','business_date',s.business_date,'submitted_at',max(r.submitted_at),'submitted_by',coalesce(max(p.full_name),s.supervisor_name_snapshot),'completion',100,'issue_count',(select count(*)from public.cold_storage_issues i where i.submission_id=s.id),'status',case when exists(select 1 from public.cold_storage_issues i where i.submission_id=s.id)then'issues_found'else'compliant'end)
   from public.cold_storage_submissions s join public.cold_storage_readings r on r.submission_id=s.id and r.submitted_at is not null left join public.profiles p on p.id=r.submitted_by_user_id where s.organization_id=c.organization_id and s.branch_id=c.branch_id group by s.id
   union all
   select s.id,s.business_date,s.submitted_at,'sales_tracking',pg_catalog.jsonb_build_object('id',s.id,'branch_id',s.branch_id,'checklist_type','sales_tracking','business_date',s.business_date,'submitted_at',s.submitted_at,'submitted_by',coalesce(p.full_name,s.supervisor_name_snapshot),'completion',100,'issue_count',0,'status','compliant')from public.sales_tracking_reports s left join public.profiles p on p.id=coalesce(s.submitted_by_user_id,s.supervisor_user_id)where s.organization_id=c.organization_id and s.branch_id=c.branch_id and s.state='submitted'
   union all
   select r.id,r.purchase_date,r.created_at,'purchase_log',pg_catalog.jsonb_build_object('id',r.id,'branch_id',r.branch_id,'checklist_type','purchase_log','business_date',r.purchase_date,'submitted_at',r.created_at,'submitted_by',p.full_name,'completion',100,'issue_count',0,'status','recorded')from public.branch_purchase_logs r left join public.profiles p on p.id=r.created_by where r.organization_id=c.organization_id and r.branch_id=c.branch_id
   union all
   select r.id,(r.created_at at time zone b.timezone)::date,r.created_at,'supplier_receiving',pg_catalog.jsonb_build_object('id',r.id,'branch_id',r.branch_id,'checklist_type','supplier_receiving','business_date',(r.created_at at time zone b.timezone)::date,'submitted_at',r.created_at,'submitted_by',p.full_name,'completion',100,'issue_count',0,'status','recorded')from public.branch_supplier_receivings r join public.branches b on b.id=r.branch_id left join public.profiles p on p.id=r.created_by where r.organization_id=c.organization_id and r.branch_id=c.branch_id
  )q where target_checklist_type is null or q.checklist_type=target_checklist_type
 )x);
exception when no_data_found or too_many_rows then raise exception'report access denied'using errcode='42501';end$$;

alter function public.get_phase2_branch_report_detail(uuid,uuid) rename to get_phase2_branch_report_detail_core;
create function public.get_phase2_branch_report_detail(actor_user_id uuid,target_report_id uuid)
returns jsonb language plpgsql stable security definer set search_path=''as $$declare result jsonb;begin
 select pg_catalog.jsonb_build_object('id',r.id,'branch_id',r.branch_id,'branch_name',b.name,'business_date',r.purchase_date,'checklist_type','purchase_log','definition_id','purchase_log_v1','submitted_at',r.created_at,'submitted_by',p.full_name,'completion',100,'issue_count',0,'status','recorded','items',pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_object('item_id',r.id,'item_text',r.item_name,'answer',r.payment_status,'remark',concat_ws(' · ',r.quantity::text||' × '||r.amount::text,r.vendor_name,r.notes))))into result from public.branch_purchase_logs r join public.branches b on b.id=r.branch_id left join public.profiles p on p.id=r.created_by where r.id=target_report_id and private.actor_can_read_operational_branch(actor_user_id,r.branch_id);
 if result is not null then return result;end if;
 select pg_catalog.jsonb_build_object('id',r.id,'branch_id',r.branch_id,'branch_name',b.name,'business_date',(r.created_at at time zone b.timezone)::date,'checklist_type','supplier_receiving','definition_id','supplier_receiving_v1','submitted_at',r.created_at,'submitted_by',p.full_name,'completion',100,'issue_count',0,'status','recorded','items',pg_catalog.jsonb_build_array(pg_catalog.jsonb_build_object('item_id',r.id,'item_text',coalesce(r.supplier_name_en,r.supplier_name_ar),'answer',r.category,'remark',concat_ws(' · ',r.quantity::text||' '||r.unit,r.notes))))into result from public.branch_supplier_receivings r join public.branches b on b.id=r.branch_id left join public.profiles p on p.id=r.created_by where r.id=target_report_id and private.actor_can_read_operational_branch(actor_user_id,r.branch_id);
 if result is not null then return result;end if;
 return public.get_phase2_branch_report_detail_core(actor_user_id,target_report_id);
end$$;

revoke all on function public.list_phase2_branch_reports(uuid,uuid,int,int,text),public.get_phase2_branch_report_detail(uuid,uuid),public.get_phase2_branch_report_detail_core(uuid,uuid)from public,anon,authenticated;
grant execute on function public.list_phase2_branch_reports(uuid,uuid,int,int,text),public.get_phase2_branch_report_detail(uuid,uuid),public.get_phase2_branch_report_detail_core(uuid,uuid)to service_role;
